GlasgowEmbedded/glasgow

gateware/mpsse.py
Implements TMS MPSSE commands and adds tests for same.
=> Implement TMS commands

gateware/mpsse.py
Implement TDO input and a test for same. Test isn't very good because I didn't do anything creative with the testbench and loopback doesn't work yet. Loopback PR will improve this test.
=> Implement TDO input.

gateware/mpsse.py
=> Implement loopback commands

software/glasgow/device/hardware.py
=> software: Don't request RAM writes of > 4096 bytes

software/glasgow/applet/interface/spi_master/__init__.py, software/glasgow/applet/program/ice40_sram/__init__.py
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> applet.program.ice40_sram: Rewrite to use the SPIMaster applet as base

software/glasgow/applet/program/ice40_sram/__init__.py
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
=> applet.program.ice40_sram: Fix obvious indent error in CDONE poll loop

hardware/boards/glasgow/glasgow.kicad_pcb
as discussed on irc
picture:
https://postimg.cc/jw61xwFs
=> revC1: add caution text about screw & washer conflicts to drawings layer

software/glasgow/applet/internal/benchmark/__init__.py
* latency: host sends one packet, device sends it back, time until the packet is received back
on the host is measured
(simulates cases where a transaction with the DUT relies on feedback from the host;
also useful for comparing different usb stacks or usb data paths like hubs or network bridges)
=> applet.internal.benchmark: add latency benchmark

software/glasgow/applet/interface/i2c_master/__init__.py
"scan" scans for i2c devices on read and write addresses in one go.
Some devices only ACK one of the addresses, so scanning both gives
a better overview of the bus. With this command you don't need to
do a "scan-read" and then a "scan-write" to get the result.
=> applet.interface.i2c_master: add "scan" command

hardware/boards/glasgow/revC1/bom.csv
It was missing a few columns which some tools including the github preview don't like
=> Fix formatting issue on BOM revC1 line 21

.travis.yml, software/glasgow/gateware/analyzer.py, software/test.py
The latter are being tracked in issue #182.
=> Add test runner script and disable broken tests

hardware/boards/glasgow/io_banks.sch
=> revC schematics: fix recommended LVDS connector

kitspace.yml
Per discussion in #193 switch to using the "multi project" kitspace yml format.
=> Add kitspace.yml for RevC1

software/glasgow/applet/interface/uart/__init__.py, software/glasgow/gateware/uart.py
Adds the --invert {RX,TX,RXTX,both,none} cli argument and the corresponding
build-time parameters to the uart gateware.
This option comes in handy when driving UART through inverting optocouplers for example.
@whitequark sorry, I haven't done a conversion to nMigen of the module. I don't have confidence in my (n)Migen skills enough for this.
=> applet.interface.uart: allow to invert the UART line signals (=idle low)

software/glasgow/applet/memory/prom/__init__.py
This patch supports use of latched shift registers to expand the pool of usable shift registers for this applet.
Additionally, it supports use of devices that need to see the address pins change in one shot such as when supporting smaller pin-compatible devices on one interface board.
=> Modified applet.memory.prom to support latching shift registers

software/glasgow/applet/interface/jtag_probe/__init__.py
I've done basic testing on a revC1, but please let me know if I should run any other checks or make any changes
```
$ glasgow run jtag-probe -V3.3 --port A --pin-tck 1 --pin-tms 2 --pin-tdi 4 --pin-tdo 3 scan            
I: g.device.hardware: building bitstream ID 7b2f28d67ee5ecae0d845d2b67c02856
I: g.cli: running handler for applet 'jtag-probe'
I: g.applet.interface.jtag_probe: port(s) A voltage set to 3.3 V
I: g.applet.interface.jtag_probe: shifted 32-bit DR=<11000010000010001000100010000010>
I: g.applet.interface.jtag_probe: shifted 8-bit IR=<10100000>
I: g.applet.interface.jtag_probe: DR segmentation discovered 1 devices
I: g.applet.interface.jtag_probe: TAP #0: IR[8] IDCODE=0x41111043
I: g.applet.interface.jtag_probe: manufacturer=0x021 (Lattice Semi.) part=0x1111 version=0x4
```
ref …
=> applet.interface.jtag_probe: convert to nmigen.

software/glasgow/applet/video/ws2812_output/__init__.py
Addresses `video.ws2812_output` item from #150
=> applet.video.ws2818_output: convert to nmigen

software/glasgow/applet/interface/uart/__init__.py
This patch addresses two issues that prevented the UART auto-baud from
operating correctly:
1. It is critically imporant that `UART.bit_cyc` is never set to zero,
doing so will render the UART gateware inoperable. To avoid this,
the `auto_cyc` register is set to "all 1s" at reset.
2. To ensure that a given initial baudrate is correctly loaded, it is
important to permit the gateware to see the `use_auto` register
with a value of `0`. This is achieved by moving the regiser write
to after the applet is reset.
If the gateware does not see the initial `0` value, then the
`bit_cyc` register's default value of `0` will remain, locking up
the UART gateware as mentioned above.
Setting a reset value for the `manual_cyc` register is not
appropriate, as this would trigger a rebuild every time the …
=> applet.interface.uart: fix auto-baud detection

software/glasgow/applet/internal/selftest/__init__.py
Addresses `internal.selftest` item from #150.
=> applet.internal.selftest: convert to nmigen

software/glasgow/applet/audio/dac/__init__.py
Addresses `audio.dac` item from #150.
=> applet.audio.dac: convert to nmigen

software/glasgow/applet/interface/ps2_host/__init__.py
Addresses `interface.ps2_host` item from #150.
=> applet.interface.ps2_host: convert to nmigen

README.md
...and the master branch is protected with review requirements
=> README: the Crowdsupply campaign is live

software/glasgow/applet/interface/uart/__init__.py, software/glasgow/gateware/uart.py
Addresses `interface.uart` item from #150.
=> applet.interface.uart: convert to nmigen

software/glasgow/applet/interface/analyzer/__init__.py
https://github.com/GlasgowEmbedded/glasgow/issues/271
=> applet.interface.analyzer: fix pullup/pulldown polarity

software/glasgow/platform/rev_c12.py
I tested this as per https://twitter.com/tom_keddie/status/1360033364829372425
Am leaving the test code here for future reference.
```
platform.add_resources([Resource("lvds",  3, Pins( "3", conn=("lvds", 0), dir="o")),
Resource("lvds",  5, Pins( "5", conn=("lvds", 0), dir="o")),
Resource("lvds",  8, Pins( "8", conn=("lvds", 0), dir="o")),
Resource("lvds",  9, Pins( "9", conn=("lvds", 0), dir="o")),
Resource("lvds", 10, Pins("10", conn=("lvds", 0), dir="o")),
Resource("lvds", 11, Pins("11", conn=("lvds", 0), dir="o")),
Resource("lvds", 14, Pins("14", conn=("lvds", 0), dir="o")),
Resource("lvds", 15, Pins("15", conn=("lvds", 0), dir="o")), 
Resource("lvds", 16, Pins("16", conn=("lvds", 0), dir="o")),
Resource("lvds", 17, Pins("17", conn=("lvds", 0), dir="o")),
Resource("lvds", 20, …
```
=> platform/rev_c12: add connector definition for the lvds connector

software/glasgow/applet/display/hd44780/__init__.py
Addresses `display.hd44780` item from #150.
Includes some trivial gateware improvements.
=> applet.display.hd44780: convert to native amaranth

software/glasgow/applet/display/pdi/__init__.py, software/glasgow/applet/interface/spi_controller/__init__.py, software/glasgow/applet/memory/_25x/__init__.py, software/glasgow/applet/program/avr/spi/__init__.py, software/glasgow/applet/program/ice40_flash/__init__.py, software/glasgow/applet/program/ice40_sram/__init__.py, software/glasgow/applet/program/nrf24lx1/__init__.py, software/glasgow/applet/radio/nrf24l01/__init__.py
Addresses a bunch of items from #150.
NOTE: only the memory-25x applet has actually been verified on hardware, the rest still need testing.
=> applet.interface.spi_controller: convert to native amaranth

software/glasgow/applet/memory/floppy/__init__.py
Addresses `memory.floppy` item from #150.
=> applet.memory.floppy: convert to native amaranth

software/glasgow/applet/video/rgb_input/__init__.py
Addresses the `video.rgb_input` item from #150.
=> applet.video.rgb_input: convert to native amaranth

software/glasgow/applet/memory/onfi/__init__.py
Addresses `memory.onfi` item from #150.
WARNING: UNTESTED ON HARDWARE
=> applet.memory.onfi: convert to native amaranth

software/glasgow/applet/audio/yamaha_opx/__init__.py
=> applet.audio.yamaha_opx: convert to native amaranth

software/glasgow/__init__.py
Replacement code has been taken straight from amaranth.
=> Don't use pkg_resources

software/glasgow/cli.py, software/glasgow/device/hardware.py
Before this commit, some aspects of factory flashing (device enumeration and initial loading of firmware) were handled in the production flow. However, this interacted poorly with the device recovery flow, since uploading a production firmware causes the device to re-enumerate.
* Re-enumeration is not very reliable, especially on Windows. (#252)
* If more than one device is connected, re-enumeration could cause the wrong one to be destructively reflashed, since USB has no geographical addressing. In addition, behavior related to `--force` depended on the device EEPROM state, which is not appropriate to either factory flashing or the recovery flows.
This commit solves these issues by separating (and simplifying) the production and the factory flashing flows.
* The production flow only …
=> Split factory flashing off into its own flow

README.md
Let me know if the rest of the paragraph should also be reworded to refer to something other than "native" tools.
=> README: Update the doco to match the change in PR#353 ("native"->"system")

software/glasgow/applet/internal/selftest/__init__.py, software/glasgow/cli.py
Mainly for @esden's factory testing.
=> Rationalize return codes

.github/workflows/main.yml
This allows more flexibility in running workflows conditionally.
=> CI: group all required workflows into one status check

software/glasgow/applet/memory/floppy/__init__.py, software/glasgow/applet/sensor/scd30/__init__.py, software/glasgow/applet/sensor/sen5x/__init__.py, software/glasgow/protocol/onfi.py, software/pyproject.toml
Fixes GlasgowEmbedded/glasgow#371
=> Replace dependency `crc` with `amaranth.lib.crc`

hardware/boards/glasgow/glasgow.sch, hardware/boards/glasgow/revC2/bom.csv
=> revC2: Corrected the CAT24M01 part number.

docs/manual/src/intro.rst
It is more natural to say "what does x look like?" or "how does x look?".
=> manual: intro: more idiomatic grammar

.github/workflows/main.yml, software/glasgow/support/plugin.py, software/pyproject.toml
=> support.plugin: add python 3.8-3.9 support

.github/workflows/main.yml, software/.gitignore, software/glasgow/support/plugin.py, software/pyproject.toml
=> Add an abominable workaround for Python 3.8-3.9

.github/workflows/main.yml
Hopefully. Our merge queue is kind of screwed right now?
=> CI: fix job skip conditions

.github/workflows/main.yml, software/glasgow/support/plugin.py, software/pyproject.toml
=> Fix issue #422

docs/manual/src/use/repl-script.rst
Sorry for a revision... there's a genuine typo, and I took the opportunity to improve clarity / wording too.
=> manual: use/repl-script: fixup typos / wording for clarity

software/pdm.min.lock, software/pyproject.toml
Our tests are currently broken in the `main` branch because we haven't before.
=> Pin Amaranth revision to a specific git commit

software/glasgow/applet/__init__.py
this is cherry picked from #486
=> test: use required_revision for assertBulids

software/glasgow/applet/program/xc9500xl/__init__.py, software/glasgow/arch/xilinx/xc9500xl.py, software/glasgow/database/xilinx/xc9500xl.py
New functionality:
- XC9500XV support
- support for programming read and write protection bits
- added `--erase` and `--verify` options to `program` operation
- blank check is performed before programming
- detects operations failing due to read and write protection
=> applet.program.xc9500xl: major refactoring.

software/glasgow/applet/interface/jtag_probe/__init__.py, software/glasgow/applet/interface/jtag_svf/__init__.py
Also does a bit of refactoring in `jtag-probe` and adds some hooks.
=> applet.interface.jtag_svf: add support for manual state transitions.

software/glasgow/applet/interface/jtag_probe/__init__.py
It is occasionally useful to shift 0 bits through DR (ie. enter Capture-DR, then go immediately to Update-DR without any Shift-DR in between), so support is added to `write_dr`, `read_dr`, and `exchange_dr` (all of which effectively do the exact same thing given 0 bits).  Shifting 0 bits through IR is basically never useful, but is supported anyway for symmetry, and to avoid state machine desync when given 0 bits anyway.
=> applet.interface.jtag_probe: add support for shifting 0 bits.

.github/workflows/cron.yml, .github/workflows/main.yml, software/glasgow/applet/internal/benchmark/__init__.py, software/glasgow/applet/internal/selftest/__init__.py
Also a random fix I am not going to bother submitting as a separate PR.
=> Minor CI improvements

software/glasgow/target/hardware.py
=> target.hardware: fix applet build on Windows

CODE_OF_CONDUCT.md
Signed-off-by: esden
Signed-off-by: marcan
Signed-off-by: Attie
=> Add a Code of Conduct documenting the existing practices

software/glasgow/applet/interface/swd_openocd/__init__.py
This is a 1:1 copy of the changes in jtag_openocd
=> swd_openocd: implement remote sleep

software/glasgow/applet/memory/_24x/__init__.py
=> Improvements for `memory-24x` applet

.github/workflows/cron.yml, .github/workflows/main.yml
Prompted by deprecation of Node v16 actions.
=> Upgrade all GitHub Actions

software/glasgow/device/hardware.py
Now that libusb will support hotplug events on Windows shortly (see libusb/libusb#1406), the hotplug wait path will get exercised. Currently it does not wait for long enough; it takes about 5.5 s on a representative Windows desktop machine used for testing.
This commit raises re-enumeration timeout to 10.0 s, and ensure that the timeout is respected no matter how many hotplug events are received. The higher fixed timeout on older libusb on Windows isn't disruptive, and with the next libusb release will become irrelevant for most.
=> Adjust re-enumeration wait parameters for Windows

software/glasgow/applet/sensor/hx711/__init__.py
=> applet.sensor.hx711: modify to use port groups.

software/glasgow/applet/memory/floppy/__init__.py
Part of #599. Largest amount of pins^Wpads^Wports so far, so an interesting test bench for the ergonomics of the new API when dealing with an unwieldy amount of I/O.
=> applet.memory.floppy: modify to use port groups.

software/glasgow/support/arepl.py
Previously this would cause a crash with an opaque `EINVAL` `OSError` that doesn't come from a syscall. (libedit why.)
Related to python/cpython#102130.
=> Upgrade Python 3.11 and earlier readline history files to Python 3.12 and later when loaded

software/glasgow/target/hardware.py
This reduces the noise from deprecation warnings somewhat.
=> Work around amaranth-lang/amaranth#1402

software/glasgow/support/arepl.py
This PR is required to avoid corrupting (double-quoting) history files after they reach the maximum length.
=> Work around more bugs in Python's `readline` module

software/glasgow/applet/interface/jtag_svf/__init__.py
=> applet.interface.jtag_svf: automatically insert DUT reset in more cases.

software/glasgow/gateware/ports.py, software/glasgow/platform/generic.py
=> Minor enhancements to internal I/O ports and port groups

software/pdm.min.lock, software/pyproject.toml
=> Upgrade to amaranth 0.5.1

software/glasgow/applet/interface/sbw_probe/__init__.py
=> applet.interface.sbw_probe: modify to use port groups

software/glasgow/applet/video/vga_output/__init__.py
=> applet.video.vga_output: modify to use port groups

software/glasgow/applet/interface/swd_openocd/__init__.py
=> applet.interface.swd_openocd: modify to use port groups

software/glasgow/applet/video/hub75_output/__init__.py
=> applet.video.hub75_output: modify to use port groups

software/glasgow/applet/video/rgb_input/__init__.py
=> applet.video.rgb_input: modify to use port groups

software/glasgow/applet/audio/yamaha_opx/__init__.py
=> applet.audio.yamaha_opx: modify to use port groups

software/glasgow/applet/interface/analyzer/__init__.py
=> applet.interface.analyzer: modify to use port groups

software/glasgow/applet/memory/onfi/__init__.py
=> applet.memory.onfi: modify to use port groups

software/glasgow/applet/program/m16c/__init__.py
Part of #599. 
Although program-m16c depends on UART which still uses pads, migrating to ports didn't break this applet.
=> applet.program.m16c: modify to use port groups

software/glasgow/applet/audio/dac/__init__.py
=> applet.audio.dac: modify to use port groups

firmware/main.c
=> firmware: Optimize code size by using goto, saving 59 bytes

firmware/main.c
Includes PR #658.
Please review only after PR #658 is merged.
=> Firmware factor out checking of direction

software/glasgow/applet/video/ws2812_output/__init__.py
=> applet.video.ws2812_output: modify to use port groups

software/glasgow/protocol/nbd.py
Depends on https://github.com/GlasgowEmbedded/glasgow/pull/585
=> protocol.nbd: implement Network Block Device server.

docs/manual/pyproject.toml, docs/manual/src/_images/revC-3drender-back.png, docs/manual/src/_images/revC-3drender-front.png, docs/manual/src/_static/styles/furo.css, docs/manual/src/conf.py, docs/manual/src/index.rst, docs/manual/src/revisions/_images/revC-3drender-back.png, docs/manual/src/revisions/_images/revC-3drender-front.png, docs/manual/src/revisions/index.rst, docs/manual/src/revisions/revC3.rst
git was being a huge pain while trying to do a rebase/squash for finalising #544, and I didn't have the spoons to fight with it, so I just moved the final document over to a new branch.
=> Finalised revC3 hardware description documentation.

docs/manual/src/conf.py, docs/manual/src/use/basic.rst, docs/manual/src/use/repl-script.rst
Spotted scanning the docs while exercising my device :3
=> docs: minor fixes.

software/glasgow/applet/interface/qspi_controller/__init__.py
This prevents reading 50/60 Hz noise from devices that do not drive their outputs (e.g. a QSPI flash that boots in QPI mode).
=> applet.interface.qspi_controller: pull up IO0/IO1 also

software/glasgow/cli.py
I noticed that while an applet is running, a full garbage collection takes ~20ms. This 20ms delay means that an applet that either sends packets/fills transfers faster than one per ~1.25ms potentially overflows. The 20ms delay is almost entirely due to the garbage collector tracking objects that exist prior to the applet running. Additionally, most of these objects do not become collectable until after the applet has finished running. Calling `gc.collect()` followed by `gc.freeze()` immediately before awaiting the applet task reduces the full gc delay to ~>1ms. I think the only downside to this addition is an additional ~20ms of delay for starting an applet.
Below are some snippets of code I used to make measurements.
By running the following code immediatly before awaiting the applet …
=> cli: call gc.freeze before awaiting applet task

software/glasgow/cli.py
This PR changes the subcommands to be created lazily. This makes argument parsing ~1.6 to 2.5 times faster depending on which subcommand was ran.
```
(main)> time glasgow -h
...
Executed in    1.32 secs    fish           external
usr time    1.18 secs    0.00 micros    1.18 secs
sys time    0.14 secs  994.00 micros    0.14 secs
```
```
(lazy_argparse)> time glasgow -h
...
Executed in  513.53 millis    fish           external
usr time  413.50 millis    0.19 millis  413.31 millis
sys time  100.27 millis    2.15 millis   98.11 millis
```
I compared tested each top level subcommand by diffing the output with respect to main (`glasgow voltage -h`, `glasgow safe -h` ...), and there were no significant differences. The differences I found were:
1. The relative order of these unmet dependencies …
=> cli: Make argparse subparser construction lazy

software/glasgow/applet/interface/analyzer/__init__.py
This change allows descriptive names to be provided to the analyser applet so the vcd files are easier to understand when you're looking at them a month later (and forgotten how it had been wired up). It will fall back to the usual `pin[index]` style if not provided.
=> applet.interface.analyzer: allow optional vcd signal names

software/glasgow/applet/video/vga_output/__init__.py
=> Improvements to the VGA output applet

examples/boilerplate.py
Supersedes and closes #663, which was more ambitious than I feel is necessary.
=> Update boilerplate applet for new APIs

software/pdm.min.lock, software/pyproject.toml
=> Bump libusb minimum version

software/glasgow/applet/program/ice40_flash/__init__.py
=> applet.program.ice40_flash: modify to use port groups

software/glasgow/applet/interface/jtag_pinout/__init__.py
=> applet.interface.jtag_pinout: modify to use port groups

software/glasgow/access/__init__.py, software/glasgow/access/direct/multiplexer.py, software/glasgow/access/simulation/multiplexer.py
Closes #599.
Thanks @isabelburgos and @q3k!
=> Remove deprecated way to instantiate pin buffers

examples/boilerplate.py, software/glasgow/abstract.py, software/glasgow/applet/__init__.py, software/glasgow/applet/debug/arm/arm7/__init__.py, software/glasgow/applet/debug/arm/arm7/test.py, software/glasgow/applet/interface/uart/__init__.py, software/glasgow/applet/interface/uart/test.py, software/glasgow/cli.py, software/glasgow/hardware/assembly.py, software/glasgow/simulation/assembly.py
=> Implement new applet API

docs/manual/src/applets/debug/arm7.rst, docs/manual/src/applets/debug/index.rst, docs/manual/src/applets/index.rst, docs/manual/src/applets/interface/index.rst, docs/manual/src/applets/interface/qspi_analyzer.rst, docs/manual/src/applets/interface/spi_analyzer.rst, docs/manual/src/applets/interface/uart.rst
=> Actually add applet docs this time

software/glasgow/applet/interface/jtag_xvc/__init__.py
Vivado no longer allows doing this from the GUI, and picks a rather high frequency by default.
=> Allow overriding frequency in JTAG XVC applet

software/glasgow/applet/interface/jtag_xvc/__init__.py
=> JTAG XVC: fix `--frequency` option

docs/manual/src/applets/interface/index.rst, docs/manual/src/applets/interface/swd_probe.rst, examples/boilerplate.py, software/glasgow/applet/__init__.py, software/glasgow/applet/interface/swd_probe/__init__.py, software/glasgow/applet/interface/swd_probe/test.py, software/glasgow/arch/arm/dap/ap.py, software/glasgow/arch/arm/dap/dp.py, software/glasgow/gateware/stream.py, software/glasgow/gateware/swd_probe.py, software/pyproject.toml, software/tests/gateware/jtag/test_probe.py, software/tests/gateware/test_swd_probe.py
This applet implements a very efficient, high speed SWD probe, but lacks any high-level functions like a debugger. All it offers out of the box is enumeration of the APs behind the DP.
=> Add an SWD probe applet

docs/manual/src/intro.rst, software/glasgow/applet/interface/swd_probe/__init__.py, software/glasgow/applet/interface/swd_probe/fixtures/test_loopback_hw.json, software/glasgow/applet/interface/swd_probe/test.py, software/glasgow/arch/arm/swj.py, software/glasgow/gateware/swd_probe.py, software/tests/gateware/test_swd_probe.py
This is essentially mandatory for interoperating with CMSIS-Packs, and for the probe-rs applet.
=> Add support for arbitrary SWJ sequences to SWD probe

firmware/fpga.c, firmware/main.c
Also fixes an out-of-bounds memory access.
=> Fix firmware crash during enumeration on Windows

software/glasgow/abstract.py, software/glasgow/applet/interface/qspi_analyzer/__init__.py, software/glasgow/applet/interface/spi_analyzer/__init__.py, software/glasgow/hardware/assembly.py, software/glasgow/simulation/assembly.py, software/glasgow/support/chunked_fifo.py, software/tests/support/test_chunked_fifo.py
This simplifies working with gateware implementing COBS.
=> Implement `AbstractAssembly.read_until`

software/glasgow/applet/interface/uart/__init__.py
Also clean up the code in general.
=> UART: fix `--stream` option handling

software/glasgow/hardware/assembly.py
Claiming an interface on Windows resets all of the sibling interfaces. It is probably not possible to make `.detach()` work properly without a lot of additional work.
This PR fixes Windows support, which is currently completely broken, so I'm going to overlook broken `.detach()` for now.
=> Claim all interfaces before pipelining IN requests

docs/manual/src/applets/interface/index.rst, docs/manual/src/applets/interface/spi_flashrom.rst, software/glasgow/abstract.py, software/glasgow/applet/interface/spi_controller/__init__.py, software/glasgow/applet/interface/spi_flashrom/__init__.py, software/glasgow/applet/interface/spi_flashrom/test.py, software/glasgow/protocol/flashrom.py
Also fixes a bug in SPI controller.
=> SPI flashrom: refactor and migrate to V2 API

software/glasgow/applet/interface/uart/__init__.py
=> UART: don't silently drop frames on overflow

docs/manual/src/applets/index.rst, docs/manual/src/applets/sensor/bmx280.rst, docs/manual/src/applets/sensor/index.rst, docs/manual/src/intro.rst, software/glasgow/applet/sensor/bmx280/__init__.py, software/glasgow/applet/sensor/bmx280/fixtures/test_bme280.json, software/glasgow/applet/sensor/bmx280/fixtures/test_bmp280.json, software/glasgow/applet/sensor/bmx280/test.py
Depends on https://github.com/GlasgowEmbedded/glasgow/pull/939.
=> Modernize `sensor-bmx280` applet

software/glasgow/applet/interface/uart/__init__.py
This sequence is similar to SSH, except it doesn't have to follow a newline. It's changed because on some non-US keyboard layouts it may be difficult to enter Ctrl+\ (issue #998), and because it was training users to use Ctrl+\ to quit other applets or modes, which sends SIGQUIT and dumps core on some OSes (issue #568).
Fixes #998.
=> applet.interface.uart: change quit sequence to `~` then `.`

.github/workflows/main.yml
This is for use with https://grebedoc.dev/
=> CI: publish site to `pages` branch
