GlasgowEmbedded/glasgow

- gateware/mpsse.py
Also allowed adjusting testbench clock divider.
> Implemented "legacy" 5x clock divider.

- gateware/mpsse.py
This implements commands 0x8E and 0x8F, the TCK-only shifts.
> Implement TCK-only shifts

- software/glasgow/applet/benchmark/__init__.py
I get the feeling that there's a reason that we're going through the MODE state but I can't figure out why. If there isn't a reason, feel free to pull this otherwise just close it!
This improves the throughput a bit.
(before)
I: glasgow.applet.benchmark: mode source: 16.999 MiB/s
I: glasgow.applet.benchmark: mode sink: 18.138 MiB/s
(after)
I: glasgow.applet.benchmark: mode source: 23.196 MiB/s
I: glasgow.applet.benchmark: mode sink: 23.840 MiB/s
> applet.benchmark: Skip going through the MODE state

- software/glasgow/access/direct/demultiplexer.py
I was getting the following when trying to run the uart applet under python 3.6.7:
```
$ glasgow run uart -V 5 tty
I: glasgow.device.hardware: device already has bitstream ID 5c5871f65cca35e67771380378527bd9
I: glasgow.cli: running handler for applet 'uart'
I: glasgow.applet.uart: port(s) A, B voltage set to 5.0 V
I: glasgow.applet.uart: running on a TTY; enter `Ctrl+\ q` to quit
File "/usr/local/bin/glasgow", line 11, in <module>
load_entry_point('glasgow==0.1', 'console_scripts', 'glasgow')()
File "/usr/local/lib/python3.6/dist-packages/glasgow-0.1-py3.6.egg/glasgow/cli.py", line 662, in main
exit(loop.run_until_complete(_main()))
File "/usr/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
return future.result()
File …
```
> access.direct.demultiplexer: fix TypeError when length is None

- software/glasgow/applet/jtag/__init__.py
- software/glasgow/applet/jtag_svf/__init__.py
I've been trying to program a bitstream generated by Project Trellis's bit_to_svf script. 
A few changes were needed to the jtag_svf applet.
* Support for exiting from Pause-DR/Pause-IR states.
* Cast the calculated pulse count for RUNTEST to an int when the value was read by the lexer as a float.
Example: `RUNTEST	IDLE	2 TCK	1E-2 SEC;`
With these changes I've been able to successfully load a bitstream into an ECP5 using Glasgow.
> applet.jtag_svf: Add compatibility SVF generated by Project Trellis

- software/glasgow/protocol/jtag_svf.py
One more change when supporting the SVF files produced by project Trellis's bit_to_svf.
* newline added inside of literals exceeding length ~100 cols.
* potential whitespace present after the newline to aid with formatting.
These are two examples from the SVF I'm working with:
```
SDR	510	TDI  (3FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF);
```
```
SDR 8000 TDI (0000000000000000000000FFDFD30000000000000000000000200000000000000000000000000000000000
000000000200000200040000000000000000000000000008000000000000000000000020000000000000000000FF5C890000
0000000000000000000000000000000000000000000000000000002000000000800000000000000000100000400200000000
00000200000000000020000000000000000000000000FFD16800000000000 …
```
> protocol.jtag_svf: Support multiline literal values.

- software/glasgow/applet/sensor/bmp280/__init__.py
URL didn't work, looks like they dropped the revision number from the filenames.
> BMP280 datasheet url changed

- hardware/boards/glasgow/glasgow-cache.lib
- hardware/boards/glasgow/glasgow.sch
- hardware/boards/glasgow/io_banks.sch
- hardware/boards/glasgow/io_buffer.sch
This is needed for 1BitSquared production management.
> revC1: Added BOM management keys to the schematic.

- software/glasgow/protocol/sfdp.py
File ".../Glasgow/software/glasgow/protocol/sfdp.py", line 151, in __init__
words = struct.unpack("4s" * 9, parameter)
struct.error: unpack requires a buffer of 36 bytes
Signed-off-by: Sylvain Munaut <tnt@246tNt.com>
> protocol.sfdp: unpack requires the exact right size

- hardware/boards/glasgow/glasgow.sch
- hardware/boards/glasgow/io_banks.sch
4 parts (J5, U8, U30, U36) were missing the MPN/Mfg schematic field values which help with automated Bill-of-Materials generation.
Also added the full variant part number for the ATECC508A. This should resolve #141
> RevC1: Added missing component MPN/Mfg values

- software/glasgow/cli.py
If you happen to use a black-on-white terminal, the regular output (info level) is white on white -> invisible. 
I tried that this afternoon while showing Glasgow on a foreign machine and was wondering why there are just empty lines on the screen and first thought the Glasgow software stack I just installed was somehow broken. While testing a few things I provoked an error and then I saw what was going on. But a new user might be lost at first.
So do not enforce white, just keep the colors as they are by default. This should produce legible
output on white-on-black and black-on-white.
The only remaining problem is the warning level: it uses yellow which is very hard to read on a white background. Maybe change the warning color to red, bold red for errors, no color differentiation for …
> cli: make output legible on black-on-white terminals too

- software/glasgow/applet/internal/selftest/__init__.py
Changes in bea50eb8 & 5506af77 broke pins-loop.
> applet.internal.selftest: fix pins-loop.

- firmware/dac_ldo.c
- firmware/glasgow.h
- software/glasgow/applet/internal/selftest/__init__.py
- software/glasgow/device/hardware.py
PIND_OEQ_N, USB_REQ_IOBUF_ENABLE and device._iobuf_enable is only relevant on revAB, on revC all of this has no effect. 
This can be confusing if you don't know about these rev differences. So add comments to the source explaining it.
> Add comments about IO-buffer enabling being only on revAB

- kitspace.yml
This allows us to pin the Kitspace page to revC1 for now and the kicad_pcb file can be used for the upcoming IBOM feature.
> Add kitspace.yml to revC1 branch

- software/glasgow/applet/internal/selftest/__init__.py
I've noticed that after running `glasgow run selftest voltage`, the outputs are left enabled.
This patch will disable the outputs after the test completes for each port.
> applet.internal.selftest: disable voltage output after test completes

- README.md
This adds some brief macOS installation instructions to the README. I've tested this and it seems to work fine.
> Add install instructions for macOS

- software/glasgow/applet/internal/selftest/__init__.py
Currently, the `glasgow run selftest pins-loop` test requires that pins are mapped as opposites / swapped (i.e: A0:A7 to B7:B0).
I don't think it's possible to achieve the required mapping with ribbon cables, as each port's data pins would end up on the opposite port's ground pins (in a cable where pin 1 maps to pin 20 on the other end).
As I have direct cables to hand (where pin 1 maps to pin 1 on both ends), I'd like to use this to perform the self test, instead of 8x jumpers.
This patch adds a `--pinmap-straight` flag that permits the "_straight-through_" A0:A7 -> B0:B7 mapping, instead of the "_straight across the board_" mapping that currently stands.
It's not likely to be beneficial for production runs where a test jig is available, but should help those who don't have access to …
> applet.internal.selftest: permit pin mapping to be direct instead of swapped

- software/glasgow/cli.py
- software/glasgow/device/hardware.py
This patchset addresses #206.
I have broken `GlasgowHardwareDevice.__init__()` in half, to better support acquiring a list of Glasgow boards, and maintaining the existing firmware loading and filtering of USB devices.
The output of `glasgow list` defaults to a text-based table - I've implemented a very simplistic table using only `str.format()` to avoid adding any dependencies.
If the user wishes, `glasgow list -j` can be used to get output as JSON instead, which can then in turn be paired with tools like `jq` to perform more complex filtering.
Examples:
```
venv:$ glasgow list
Serial              : Rev   : USB Path
------------------- : ----- : --------
C1-20200923T174926Z : revC1 : 1-4.4.4
C1-20200923T190627Z : revC1 : 1-2
```
```
venv:$ glasgow list -j
[{"serial": …
```
> Method to list connected Glasgow boards

- examples/i2c-pcf8574.py
- software/glasgow/cli.py
This patchset will add support for `run-repl --script ${FILENAME}`, permitting a user to write a python script to directly interface with the `iface`.
I have also included an example script that will communicate with a BMP085 temperature and pressure sensor.
I wonder if it might also be beneficial for the script to have access to `device`, for functions like `device.set_voltage()`. This would permit power cycling the DUT from the script if / when necessary.
> REPL script support

- software/glasgow/applet/all.py
- software/glasgow/applet/display/pdi/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/memory/_25x/__init__.py
- software/glasgow/applet/program/avr/spi/__init__.py
- software/glasgow/applet/program/ice40_sram/__init__.py
- software/glasgow/applet/program/nrf24lx1/__init__.py
- software/glasgow/applet/radio/nrf24l01/__init__.py
As discussed in `#glasgow`, this patch should update the SPI signal terms to COPI / CIPO / CS.
The old terms will no longer be obeyed, and flags such as `--pin-copi` must be used from now on.
I believe I've resolved all references to the old terms, but if there are other places (perhaps implicit) that I've missed please let me know.
Happy to squash into one commit if that would be preferred.
> Update SPI signal terms to COPI / CIPO

- software/glasgow/applet/__init__.py
While working on #213, I noticed the following error:
```
venv:$ glasgow run --help
File "/home/attie/proj_local/glasgow/venv/bin/glasgow", line 11, in <module>
load_entry_point('glasgow', 'console_scripts', 'glasgow')()
File "/home/attie/proj_local/glasgow/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/home/attie/proj_local/glasgow/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
return ep.load()
File "/home/attie/proj_local/glasgow/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
return self.resolve()
File "/home/attie/proj_local/glasgow/venv/lib/python3.8/site-packages/p …
```
> applet: fix repl format conversion

- software/glasgow/applet/interface/i2c_initiator/__init__.py
Addresses `interface.i2c_initiator` item from #150.
---
I have also made a start on the gateware, but it cannot be completed yet as `FSM.after_entering()` and `FSM.before_entering()` do not yet exist in nMigen. See: [attie:gateware-i2c](https://github.com/GlasgowEmbedded/glasgow/compare/master...attie:gateware-i2c).
> applet.interface.i2c_initiator: convert to nmigen

- software/glasgow/support/data_logger.py
This adds a new logger named ``influxdb2``.
At first I wanted to expand the existing ``influxdb`` logger, but there are a few differences between 1.x and 2.x:
* 1.x takes a ``db`` parameter
* 2.x takes ``org`` and ``bucket``
* 2.x does not support a parameter ``retention-policy`` on write, instead the retention period is configured statically on the bucket
* 2.x requires authentication with a Token
The token could have been added as an optional parameter, but the discrepancy between the single positional parameter ``db`` and the two parameters ``org`` / ``bucket`` would have been awkward.
I've tested this against a local influxdb running in docker (``docker run --rm -it --name influxdb -p 8086:8086 quay.io/influxdb/influxdb:v2.0.2``) and against the cloud version.
The invocation to log it …
> add InfluxDB2DataLogger (cli name influxdb2) to log into an InfluxDB 2.x

- software/glasgow/support/bits.py
I think you want to subtract absolute value of `key` from `_len_`, but with `_len_ - key` you get `_len_` added to the absolute value of key. 
So I propose changing the sign in the expression.
Fixes #244
> support.bits: fix __getitem__ for negative keys

- .github/workflows/main.yml
- software/setup.py
This is a first pass at using GHA instead of Travis for CI. It should perform the same actions as Travis currently does.
Currently this doesn't perform any caching; we could cache both the pip downloads for YoWASP and the built WASM objects fairly easily if that's desirable. This doesn't remove the Travis CI file either.
> Switch CI from Travis to GitHub Actions

- software/glasgow/applet/video/vga_output/__init__.py
Addresses `video.vga_output` item from #150.
This PR is WIP... there are a couple of things I'd like feedback on how best to implement.
1. Previously the clock had a constraint asserted on it in `VGAOutputApplet.build()`... this seems to be no longer possible (as `VGAOutputSubtarget.elaborate()` has not yet been called). [here](https://github.com/GlasgowEmbedded/glasgow/commit/a66fe3ab4666d7dfc8d44dad98fd4d68bca802d7#diff-d20e0211e5dd56d6d48a64583b73de982dd3f16bbdb89728f8931c560ead118bR69-R72)
2. Previously the pixel data was generated in `VGAOutputApplet.build()`, but again, this is no longer possible. [here](https://github.com/GlasgowEmbedded/glasgow/commit/a66fe3ab4666d7dfc8d44dad98fd4d68bca802d7#diff-d20e0211e5dd56d6d48a64583b73de982dd3f16bbdb89728f8931c560ead118bR124-R127)
I very …
> applet.video.vga_output: convert to nmigen

- software/glasgow/applet/__init__.py
Argument to add_clock is a period, not a frequency. A very low
frequency creates huge timestamps which overflows gtkwave.
> applet: fix simulation clock

- software/glasgow/gateware/uart.py
A fix to my mistake while rewriting in nMigen...
`value_bits_sign(sig)` -> `sig.shape()`
> gateware.uart: fixup parity handling

- examples/i2c-pcf8574.py
`glasgow run-script` -> `glasgow script`
> examples: fixup PCF8574 usage

- docs/known_issues.rst
Add details about libusb bug that may prevent glasgow from being seen by `lsusb` and `glasgow list`.
> doc: add details about libusb bug

- software/glasgow/protocol/sfdp.py
"Mbit" (Mb) per the SI multiples means 1000 Kbit, however this section of code is working with 1024 multiples, hence Mebibit (Mib).
Updated the wording to clarify this distinction
> Clarify the wording of the Flash sizes listed by the SFDP decoder

- README.md
Switch to the python3 alias so we don't hit the system Python which is a version 2.
https://github.com/GlasgowEmbedded/glasgow/issues/279#issue-817072119
> README: use `python3` to run the macOS setup script

- software/glasgow/applet/program/avr/__init__.py
- software/glasgow/applet/program/avr/spi/__init__.py
- software/glasgow/applet/program/avr/spi/fixtures/test_api_program_memory.json
- software/glasgow/database/microchip/avr.py
This patchset adds support for programming ATMega640, ATMega128x and ATMega256x parts
- Fix a bug when calling `range()` for verification - the chunks appear to be broken into 64K pieces, which may have been masked on parts with smaller memories.
- These new parts make use of a "_Load Extended Address_" instruction, to reach beyond the 17-bit limit imposed otherwise
- These new parts have 8-byte / 4-word EEPROM pages
- Add definitions for these parts
The "_Load Extended Address_" instruction is present in the datasheet for the 328p, and I have confirmed that it doesn't have any adverse side-effects when receiving it... I can't make that claim for other parts, but could probably dig out a couple of other parts...
This has been tested against a 328p, and a 2560.
> add support for ATtiny26, ATmega640, ATmega128x and ATmega256x

- software/glasgow/applet/all.py
- software/glasgow/applet/sensor/sen5x/__init__.py
This adds a new applet to support Sensirion's [SEN5x](https://developer.sensirion.com/jp/sensirion-products/sen5x-environmental-sensor-node/) PM/NOx/VOC/RH/T sensor nodes, based on the SCD30 applet.
Some example usage:
```
$ glasgow run sensor-sen5x -V 5 --port A --pin-sda 0 --pin-scl 1 --pulls start
I: g.device.hardware: device already has bitstream ID c30451fc79714b15a8e9f3e09c533c99
I: g.cli: running handler for applet 'sensor-sen5x'
I: g.applet.sensor.sen5x: port(s) A voltage set to 5.0 V
I: g.applet.sensor.sen5x: port(s) A pull resistors configured
I: g.applet.sensor.sen5x: SEN5x: SEN55 serial [xxx] firmware v1
$ glasgow run sensor-sen5x -V 5 --port A --pin-sda 0 --pin-scl 1 --pulls measure
I: g.device.hardware: device already has bitstream ID c30451fc79714b15a8e9f3e09c533c99
I: …
```
> applet.sensor.sen5x: add applet for Sensirion SEN5x

- software/glasgow/applet/interface/uart/__init__.py
This PR fixes a crash when running the `uart tty` subcommand on Windows. It does not allow sending `^C` like on *nix, but at least the command is usable at all.
> applet.interface.uart: fix `tty` subcommand on Windows

- software/glasgow/applet/interface/uart/__init__.py
Make the autobaud limitations more visible and expand details in `UARTAutoBaud`'s docstring.
Supersedes #260.
> applet.interface.uart: add commentary about the autobaud and its limitations

- software/glasgow/applet/interface/jtag_svf/__init__.py
Some SVF producers (like Xilinx impact) emit a TRST OFF command as part of the initialization.  This has no effect other than bringing the system to the default state, so ignoring it when there is no TRST# pin is harmless.  Likewise, ignore TRST Z in this case.
> applet.interface.jtag_svf: ignore TRST OFF when TRST# not present

- README.md
- software/glasgow/applet/memory/floppy/__init__.py
- software/glasgow/applet/sensor/scd30/__init__.py
- software/glasgow/applet/sensor/sen5x/__init__.py
- software/glasgow/arch/nrf24l/__init__.py
- software/glasgow/protocol/onfi.py
- software/pyproject.toml
This is a continuation / re-PR of PR #310.
Ports crcmod to crc as requested in issue #309.
**Tested this way:**
testdata=b"\x12\x23\x34\x56\xaa\xbb\xcc\xdd"
import crc
import crcmod
crc_mfm_new = staticmethod(crc.Calculator(crc.Configuration(width=16, polynomial=0x11021, init_value=0xffff)).checksum)
crc_mfm = staticmethod(crcmod.mkCrcFun(0x11021, initCrc=0xffff, rev=False))
print("Bad crc") if crc_mfm_new(testdata)!=crc_mfm(testdata) else print("All fine :)")
> Port crcmod to crc

- .github/workflows/main.yml
With the move away from amaranth.compat almost complete, the tests are now free from deprecation warnings.
> CI: unignore DeprecationWarning

- software/glasgow/access/__init__.py
- software/glasgow/gateware/pads.py
- software/glasgow/target/hardware.py
This removes the last dependency on `amaranth.compat`, finishing the migration.
Depends on amaranth-lang/amaranth#833 .
> software: move from `TSTriple` to `Pin`, simplify `Pads`

- software/pyproject.toml
The latter is overly strict and breaks installation with PDM (which is more principled than our other PEP517 build backends).
> pyproject: setuptools~=67.0 → setuptools>=67.0

- .gitignore
- README.md
- software/.gitignore
- software/glasgow/cli.py
- software/glasgow/target/hardware.py
- software/glasgow/target/toolchain.py
- software/pyproject.toml
This commit adds a mechanism to Glasgow similar to the existing `AMARANTH_USE_YOSYS` mechanism that selects a Yosys binary to run. It introduces the concept of a toolchain (a collection of tools that come from a single source; currently, either the system binaries or the co-installed YoWASP packages). The toolchain is used as a whole, i.e. system and YoWASP packages cannot be mixed since this has a high probability of being a mistake. Any missing components required for operation are reported.
To select the toolchain, a new `GLASGOW_TOOLCHAIN` environment variable is introduced. It can be set to `builtin`, `system`, or a comma separated list where earlier entry has priority.
The default is `builtin,system` to make YoWASP packages take priority since when installed with pipx or pdm, these …
> target: locate and examine the FPGA build tools

- software/glasgow/applet/__init__.py
- software/glasgow/cli.py
- software/glasgow/device/hardware.py
- software/glasgow/target/hardware.py
- software/pyproject.toml
This is a major usability improvement for two use cases:
* routine and recommended use of the reset button on revC2+, which is otherwise excruciatingly slow;
* frequent switching between multiple specific applet configurations, useful as a workaround for the lack of multiple applet support.
This commit should make most uses of `run --prebuilt` obsolete.
Fixes #43 (again).
Depends on #353.
> target: cache bitstreams

- .github/workflows/main.yml
- software/glasgow/applet/__init__.py
- software/glasgow/target/toolchain.py
- software/pyproject.toml
At the moment (since commit 36769e73) synthesis tests are not running on CI because a request to install nonexistent optional dependency group is silently ignored by pip.
Pip is not really suited for this workflow, so use PDM instead, and also set up the `pdm run test` alias since the test runner is liable to change in the future.
> software: use PDM to manage dependencies on CI

- software/glasgow/cli.py
- software/glasgow/device/hardware.py
For example:
$ glasgow voltage
Port    Vio     Vlimit  Vsense  Monitor
A       0.0     5.5     0.0     0.0-5.5
B       0.0     3.3     0.0     0.0-5.5
$ glasgow voltage AB 5
E: g.cli: cannot set I/O port(s) AB voltage to 5.0 V (port B voltage limit is set to 3.3 V)
It is easy to miss the value in the Vlimit column. The display of causes of the error avoids a source of frustration, and ensures that voltage limit caused errors do not mislead the operator into thinking that their device is faulty.
> device.hardware: print causes of `set_voltage()` failure

- software/pyproject.toml
PDM 2.8.1 has fixed the bug that prevented its use before.
> Use proper `amaranth[builtin-yosys]` dependency

- CODEOWNERS
- software/glasgow/applet/video/hub75_output/__init__.py
- software/pyproject.toml
This patch implements a basic test pattern generator for HUB75 LED Matrix panels, much like the VGA output applet.
The output is only 3-bit / 8-color, with no attempt at producing more colors or brightness control.
Panels of various shapes and sizes are supported, I've developed with a 64x64 1/32 scan panel, and have also tested with a second connected to produce a resolution of 128x64.
> applet.video.hub75_output: implement basic HUB75 test pattern generator

- CODEOWNERS
- software/glasgow/applet/video/ws2812_output/__init__.py
This sits on top of #224, and adds the ability to give other pixel formats.
I've backed down from the more complex options, and have opted for a simple lambda function that constructs the final pixel shape, paired with `-f`, e.g:
- `-f RGB-BRG`
- `-f RGB-xBRG` - for use with RGBW LEDs, with the White blanked to zero
- `-f RGBW-WBRG`
```python
pixel_formats = {
'RGB-BRG':   (   3,        3,    lambda r,g,b:   Cat(b,r,g)   ),
'RGB-xBRG':  (   3,        4,    lambda r,g,b:   Cat(Const(0, unsigned(8)),b,r,g) ),
'RGBW-WBRG': (   4,        4,    lambda r,g,b,w: Cat(w,b,r,g) ),
}
```
```python
p = self.pix_format_func(*pix, self.out_fifo.r_data)
m.d.sync += word.eq(Cat(word[pix_out_bpp:], p))
```
> applet.video.ws2818_output: add support for LEDs other than RGB

- software/glasgow/target/hardware.py
It is used by wasmtime-py to determine which DLL to load.
Fixes #383.
> target.hardware: whitelist `PROCESSOR_ARCHITECTURE`

- software/glasgow/device/hardware.py
On Linux multiple userspace applications can send control requests to a device without being aware of each other. Claim every interface to ensure mutual exclusion with any other application.
On other OSes device access is already exclusive.
Fixes #241.
Nudge the operator to reflash obsolete devices.
Fixes #239.
Closes #247.
> device.hardware: check if device is busy before loading firmware

- software/glasgow/applet/internal/selftest/__init__.py
Fixes the following error:
TypeError: Object flipped((rec led_0 o)) cannot be converted to an Amaranth value
Tested on revC3-ish.
> applet.selftest: fix `leds` mode.

- firmware/main.c
The issue #382 (failure of the device to enumerate when plugged into a Windows machine for the first time) was caused by the lack of handling of a Windows-specific descriptor. Respond to a request for this descriptor.
Fixes #382.
> firmware: fix issue #382

- .github/workflows/main.yml
- firmware/.gitignore
- firmware/Makefile
- firmware/main.c
In the issue #382, @VioletEternity pointed out that it is not currently possible to find out which git commit a firmware was built.
This commit introduces the embedding of the hash of the commit containing the last modification to the `firmware/` (git) tree in the product string that is visible in the device properties, for example on Linux it can be retrieved like this:
```
$ lsusb -d 20b7:9db1 -v | grep iProduct
iProduct                2 Glasgow Interface Explorer (git 52734ce9)
```
Because a commit cannot include its own hash (without a successful preimage attack on SHA1), the commit that is updating the built-in firmware in the `software/glasgow/device/firmware.ihex` file needs to be separate from the commit that updates the firmware code. Because the version is recorded for the …
> firmware: include git revision in product string

- .github/workflows/main.yml
- docs/manual/src/index.rst
It is unclear whether services will follow the meta redirect on the landing /index.html page, but it seems the answer is "probably not". Be safe and add the metadata both on /index.html and /latest/index.html, for good measure.
Fixes #401.
> manual: index: add opengraph and twitter metadata

- docs/manual/src/conf.py
This bothered me for a while.
(It's not visible in the docs built from the PR--you'll have to check out locally.)
> manual: make the call-to-action announcement green

- examples/script_args.py
- software/glasgow/applet/__init__.py
- software/glasgow/cli.py
As discussed in `#glasgow`, it would be nice to make command line arguments available to the REPL and script environments (especially the latter).
This patch adds support for this, with a small example script.
> cli: add support for passing command-line arguments to the REPL and script environments

- software/glasgow/applet/audio/yamaha_opx/__init__.py
- software/glasgow/applet/audio/yamaha_opx/index.html
The `audio-yamaha-opx` applet potentially allows remote users to make GET requests to arbitrary URLs. This may have security implications (e.g., accessing internal IP addresses, or accessing prohibited URLs). This patch disables this feature by default, but allows users to opt back in by passing the `--allow_urls` flag to the `audio-yamaha-opx` applet.
> Add --allow_urls option to audio-yamaha-opx applet

- software/glasgow/applet/audio/yamaha_opx/__init__.py
This resolves an issue where you can't specify an IPv6 endpoint like '[2602:fce8:101:69:d886:936e:f259:3927]:3128'
> applet.audio.yamaha_opx: fix listening on IPv6 endpoints

- docs/manual/src/contribute.rst
- software/glasgow/cli.py
Fixes #400.
Output looks like this:
```
$ pdm run glasgow --version
Glasgow 0.1.dev1826+g4fe4acc.d20231004164618 (CPython 3.9.18 on Linux-6.1.0-10-amd64-x86_64-with-glibc2.37)
$ pdm run glasgow --version
Glasgow 0.1.dev1825+gcc2acdc (CPython 3.11.2 on Linux-6.1.0-10-amd64-x86_64-with-glibc2.36 Debian GNU/Linux 12 (bookworm))
% pdm run glasgow --version
Glasgow 0.1.dev1889+gb95a16e (CPython 3.11.5 on macOS-13.4.1-arm64-arm-64bit)
>pdm run glasgow --version
Glasgow 0.1.dev1891+g3833fcb (CPython 3.11.4 on Windows-10-10.0.19045-SP0)
```
> cli: add platform, architecture, and OS version to `--version` output

- .github/workflows/main.yml
aiohttp still doesn't work on 3.12, but that's mostly out of our hands.
> Python 3.12 is released, 3.13-dev is the next development snapshot

- software/glasgow/protocol/jesd3.py
Originally proposed in whitequark/prjbureau#13.
> protocol.jesd3: fix detection of default fuse state in a JED file

- docs/manual/src/develop/docs.rst
- docs/manual/src/use/repl-script.rst
Finally, some words around using the REPL and script interfaces... I've included I2C, UART and WS2812 demos... I'll happily have a rummage for an SPI device to add that if it's deemed important.
> manual: use/repl-script: add details about the REPL and Script interfaces, along with examples

- hardware/boards/glasgow/glasgow.kicad_pcb
Due to potential shorts users might experience we need to have a reference of where the case can overlap with the circuits on the PCB. The outlines are added to the optional user.1 and user.2 layers.
The case to board tolerance is 0.4mm. The lines are doubled to represent the maximum overlap extents.
> revC3: Added aluminium case outline with tolerance.

- software/glasgow/applet/program/xc9500xl/__init__.py
- software/glasgow/protocol/jesd3.py
This affects both Linux and Windows platforms whenever CRLF newlines are used.
Fixes #367.
> Fix JESD3 lexer to ensure checksum computes correctly no matter which newlines are used

- software/.gitignore
- software/glasgow/device/hardware.py
- software/pyproject.toml
- software/setup.py
This provides us with the same functionality as setuptools with none of the legacy complexity and issues.
It also means that we use the same vendor for our package management and package build system, reducing the fragmentation in our dependency tree. (We went from three independent code suppliers to one.)
> Migrate to the PDM-Backend build backend

- software/glasgow/cli.py
- software/glasgow/device/hardware.py
- software/glasgow/support/task_queue.py
"Surprise disconnected" means disconnecting a device while it is being used by an applet, script, or REPL; whether there are ongoing transfers or not.
After this commit, in general, only one message should be printed:
```
E: g.cli: device disconnected
```
However, applet logic will often not handle cancellation or USB transfer errors, so certain individual applets may still print more noise.
This has been one of the more irritating papercuts, especially as all that noise will make recovering from an accidentally unplugged device all that more annoying, and it's confusing to people who have not seen the error before too.
See individual commit messages for details of implementation, which is _nightmarish_.
Fixes #386.
> Do not fill terminal with noise when a device is surprise disconnected

- software/glasgow/applet/display/pdi/__init__.py
- software/glasgow/applet/program/xc6s/__init__.py
- software/glasgow/applet/program/xc9500xl/__init__.py
- software/glasgow/protocol/jesd3.py
- software/glasgow/support/bits.py
- software/pyproject.toml
- software/tests/support/test_bits.py
> software: migrate away from `bitarray` dependency.

- software/glasgow/cli.py
- software/glasgow/support/plugin.py
This most notably improves the case where stale entry points metadata refers to a nonexistent applet (e.g. because it was removed, or because the applet was developed in a different branch of an editable install), which before this commit entirely breaks the CLI. This commit catches load errors and displays a nice error message in the UI.
This commit also improves help text for plugins with unmet requirements.
> Gracefully handle plugin load errors

- docs/manual/src/conf.py
- docs/manual/src/develop/firmware.rst
[Rendered](https://whitequark.github.io/glasgow/manual-develop/firmware/develop/firmware.html)
> manual: develop/firmware: write the page

- docs/manual/src/develop/firmware.rst
unrelated to this patch, but did you know the github web editor inserts newlines at the end of files whether you want them or not? Maybe a .editorconfig file fixes it...
> manual: develop/firmware: extremely minor grammar fix

- .github/workflows/main.yml
- software/glasgow/target/hardware.py
- software/pdm.min.lock
- software/pyproject.toml
platformdirs is a friendly, maintained fork of appdirs (which stopped development after ~2020) - This should be 100% compatible for the used method.
I'm not exactly sure about the PDM lock file, getting rid of appdirs there might be dependent on https://github.com/YoWASP/runtime/pull/2 ?!?
> Migrate from appdirs to platformdirs

- software/glasgow/support/bits.py
- software/pdm.min.lock
- software/pyproject.toml
Is this a policy change? Yes: I'm looking to gradually add typing annotations (specifically the Pylance dialect) to Glasgow, and then eventually to Amaranth.
> Add type annotations to all public methods in `support.bits`

- software/glasgow/device/hardware.py
- software/pdm.min.lock
- software/pyproject.toml
**WIP: requires libusb1 version bump after https://github.com/vpelletier/python-libusb1/issues/90 is merged.**
While performing `USBContext.handleEvents()` the poller thread is uninterruptible other than through libusb1 API. Since the Python runtime joins all non-daemon threads on threading shutdown it is necessary to interrupt the thread by calling the corresponding libusb1 function.
A seemingly obvious solution is to make the thread a daemon thread so that it is not joined on threading shutdown. Unfortunately this only makes the problem worse. All daemon threads are instantly killed, leaving a lock within libusb1 permanently taken, and causing a hang later when python-libusb1 objects are garbage collected.
Fixes #413.
> Interrupt USB polling thread before threading shutdown

- examples/out_of_tree/.gitignore
- examples/out_of_tree/README.md
- examples/out_of_tree/glasgowcontrib/applet/exampleoot/__init__.py
- examples/out_of_tree/pyproject.toml
- software/glasgow/cli.py
- software/glasgow/support/plugin.py
If `GLASGOW_OUT_OF_TREE_APPLETS` environment variable is not set to `I-am-okay-with-breaking-changes` then the software stack behaves exactly as before. If it is, a warning is printed anyways. I think this is a good compromise to allow us to proceed with enabling *some* out-of-tree applet use without locking ourselves into an API we don't want to keep.
We may regularly change the `GLASGOW_OUT_OF_TREE_APPLETS` code phrase to make sure people do not get complacent about it and use OOT applets for more than experimenting.
> support.plugin: add feature-gated support for out-of-tree applets

- software/glasgow/access/__init__.py
- software/glasgow/access/direct/arguments.py
- software/glasgow/access/simulation/arguments.py
this fixes an error where _arg_error would fail in a different than expected way. Also unneeded argparse import in SimArguments.
> access.args: fix argparse import

- CODEOWNERS
- software/glasgow/applet/__init__.py
- software/glasgow/applet/control/servo/__init__.py
- software/glasgow/applet/control/servo/test.py
- software/pyproject.toml
Right now this supports only a single channel and a fixed minimum/maximum/update frequency (1ms/2ms/50 Hz). These restrictions can be relaxed in the future if this is desired.
This is a REPL-only applet (which in itself is a new category established in this PR). It doesn't feel like ther's a good way to make a CLI for servos, and having only a REPL makes snense here.
This applet can also serve as an example of a rather simple applet that follows the latest best practices.
> applet.control.servo: an applet for controlling servomotors and brushless ESC modules

- software/glasgow/support/arepl.py
Allows easy access to e.g. `asyncio.sleep`.
Maybe it would be better to just have `sleep` available and point to `asyncio.sleep`?
> support.arepl: make asyncio `sleep` available by default

- software/glasgow/cli.py
I attached an older, C1-like glasgow which was untouched for some time and got told its API level 1 was too old:
```
$ glasgow list
I: g.device.hardware: found revC1 device with API level 1 (supported API level is 2)
W: g.device.hardware: please run `glasgow flash` to update firmware of device C1-20191109T210718Z
C1-20191109T210718Z
```
Trying the suggested "glasgow flash" command lead to an error:
```
$ glasgow flash
I: g.cli: reading device configuration
I: g.cli: device has serial C1-20191109T210718Z
I: g.cli: device has flashed firmware
I: g.cli: device does not have flashed bitstream
I: g.cli: using built-in firmware
File "/home/moritz/.local/bin/glasgow", line 8, in <module>
sys.exit(main())
^^^^^^
File …
```
> software: fix "glasgow flash" command

- examples/boilerplate.py
This applies the following commit to boilerplate.py as well:
- 9ff95922 ("applet: kill `all`, use Python entry points to declare applets.")
> Update boilerplate applet

- software/glasgow/applet/interface/jtag_probe/__init__.py
For now it simply calls JTAGProbeInterface.flush()
This is in order to make higher level JTAG code more readable, so not too many .lower's need to be chained.
> applet.interface.jtag_probe: add flush() method to TAPInterface

- software/glasgow/gateware/fx2_crossbar.py
This was removed after Amaranth 0.4.
> software: remove uses of deprecated `fwft` parameter

- software/glasgow/applet/debug/arc/__init__.py
- software/glasgow/applet/program/mec16xx/__init__.py
- software/glasgow/arch/arc/core.py
- software/glasgow/arch/arc/mec16xx.py
Please see individual commits for details and commit messages.
Let me know if you'd want to split this up as separate PRs.
In short:
- Arc is halted correctly
- Fixed bug with the write subcommand failing
- Added support for accessing eeprom
- Added erase-flash subcommand
> Improvements for mec16xx

- software/glasgow/applet/interface/jtag_openocd/__init__.py
Sometimes it's useful to trigger a DUT reset from within JTAG-adjacent logic. For example OpenOCD uses this feature as part of its remote-bitbang protocol, and the [ARM 20-pin JTAG connector](https://developer.arm.com/documentation/dui0499/k/arm-dstream-target-interface-connections/the-arm-jtag-20-connector-pinouts-and-interface-signals/arm-jtag-20-pinouts?lang=en) includes an SRST# pin. This PR adds SRST# support to the jtag-probe and jtag-openocd applets.
- The SRST pin could be added to jtag-openocd only, as it's not strictly part of a JTAG interface.
- SRST could be renamed RESET, but I think that would be more ambiguous.
> SRST# support in jtag-openocd

- software/glasgow/applet/interface/jtag_pinout/__init__.py
If the user has selected a non-default port spec, print it in the suggested command line, to ensure that the suggested pin numbers are correct.
> applet.interface.jtag_pinout: Include --port in suggested arguments

- software/glasgow/access/simulation/multiplexer.py
- software/glasgow/gateware/analyzer.py
It is no longer present in Amaranth 0.5, and it defaults to `True` in Amaranth 0.4 anyway.
> software: remove uses of the deprecated `fwft` parameter.

- software/glasgow/applet/internal/benchmark/__init__.py
- software/glasgow/applet/internal/selftest/__init__.py
I'm not sure why that change is in commit 5e1f94dd--it may be unintentional?
> applet.internal.{benchmark,selftest}: fix after commit 5e1f94dd

- CODEOWNERS
It changed at the last minute; update CODEOWNERS too.
> CODEOWNERS: fix spi_flashrom applet name

- software/glasgow/applet/interface/swd_openocd/__init__.py
- software/glasgow/applet/interface/swd_openocd/test.py
- software/pyproject.toml
Requires a pre-release version of openocd. Works fine here with a random STM32F1:
```
$ ../src/openocd -c 'adapter driver remote_bitbang; transport select swd; remote_bitbang port 2222' -f target/stm32f1x.cfg
Open On-Chip Debugger 0.12.0+dev-03105-g07141132a (2024-03-06-04:16)
Licensed under GNU GPL v2
For bug reports, read
http://openocd.org/doc/doxygen/bugs.html
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : Initializing remote_bitbang driver
Info : Connecting to localhost:2222
Info : remote_bitbang driver initialized
Info : Note: The adapter "remote_bitbang" doesn't support configurable speed
Info : SWD DPIDR 0x2ba01477
Info : [stm32f1x.cpu] Cortex-M3 r2p1 processor detected
Info : [stm32f1x.cpu] target has 6 breakpoints, 4 …
```
> applet.interface.swd_openocd: new applet

- software/glasgow/applet/interface/analyzer/__init__.py
After upgrading Yosys to 0.39, the applet stopped passing timing when built for revA. This was reported against Yosys (YosysHQ/yosys#4280), but as there don't seem to be any commits that could change synthesis quality, it was likely just that the analyzer applet was marginal in first place.
Since this is blocking all further development, the applet is now restricted to revC0+.
> applet.interface.analyzer: restrict to revC0+

- software/glasgow/applet/video/vga_output/__init__.py
In the past nextpnr-ice40 was not able to infer it, but now it produces a warning:
Warning:     Overriding derived constraint of 25.3 MHz on net multiplexer.U$$0.U$$0.pix_clk with user-specified constraint of 25.2 MHz.
> applet.video.vga_output: remove unnecessary clock constraint

- software/glasgow/applet/interface/spi_flashrom/__init__.py
Just a very small fix for the example cmdline given in the new spi-flashrom applet.
Thanks to everyone involved with it, I've been using it for the last days, it works very well 😎
> applet.interface.spi_flashrom: documentation, spi-serprog -> spi-flashrom

- software/glasgow/device/hardware.py
If any of the USB devices attached are busy or unavailable, but libusb1 sees them, you get a nice trace on Windows:
```
$ glasgow list
File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\WPy64-31080\python-3.10.8.amd64\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\users\c_ofl\.local\bin\glasgow.exe\__main__.py", line 7, in <module>
File "C:\ChipWhisperer5_64_5_7_0\cw\home\portable\chipwhisperer\jupyter\user\glasgow\glasgow\software\glasgow\cli.py", line 937, in main
exit(loop.run_until_complete(_main()))
File …
```
> device.hardware.py: Add skip_on_error flag to improve Windows experience with USB discovery

- software/glasgow/cli.py
It feels like a waste to make  PR for, but I don't want to throw it in with unrelated things... feel free to fix yourself & close this if easier!
> cli.py: Fix small typo ("f{arg} -> f"{arg})

- software/pyproject.toml
In [project.urls], the URL of the Glasgow repository is misspelled.
> Fix typo in pyproject.toml

- software/glasgow/applet/interface/jtag_openocd/__init__.py
Note: This PR has prerequesites:
And a TODO list:
> applet.interface.jtag_openocd: implement remote sleep

- software/glasgow/gateware/accumulator.py
- software/glasgow/gateware/registers.py
- software/glasgow/support/asignal.py
- software/glasgow/support/os_network.py
- software/tests/gateware/test_accumulator.py
This is a rollup PR of several pending improvements that I have:
- a fix for an annoying `asignal` bug which would sometimes show a backtrace on ^C
- an improvement to the `registers` module that improves compatibility with components and reduces boilerplate, extracted from #483
- throughput improvements for the Linux TAP interface driver
- a new pipelined accumulator module that can be used for things such as packet counters, without affecting your timing no matter how fast you're going, as long as you don't need the results right away
> Various improvements

- software/pdm.min.lock
- software/pyproject.toml
The only change in this major version bump was to `site_cache_dir` (/var/cache instead of /var/tmp), but Glasgow only relies on `user_cache_dir` and is unaffected by this.
For reference: [platformdirs diff (3.11.0...4.0.0)][1]
[1]: https://github.com/platformdirs/platformdirs/compare/3.11.0...4.0.0
> software: bump platformdirs upper bound

- software/glasgow/cli.py
- software/pyproject.toml
This avoids a warning on Python 3.12.
> cli: use `asyncio.run()`

- software/glasgow/applet/interface/uart/__init__.py
As far as I know there are no UART configs with more than 1 start bit. I guess it should be "data" bits.
> Fix small detail in uart applet doc

- software/glasgow/access/__init__.py
- software/glasgow/access/direct/multiplexer.py
- software/glasgow/access/simulation/multiplexer.py
- software/glasgow/applet/__init__.py
- software/glasgow/applet/audio/yamaha_opx/__init__.py
- software/glasgow/applet/control/servo/__init__.py
- software/glasgow/applet/display/pdi/__init__.py
- software/glasgow/applet/interface/jtag_openocd/__init__.py
- software/glasgow/applet/interface/jtag_probe/__init__.py
- software/glasgow/applet/interface/ps2_host/__init__.py
- software/glasgow/applet/interface/sbw_probe/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/interface/swd_openocd/__init__.py
- software/glasgow/applet/interface/uart/__init__.py
- software/glasgow/applet/memory/onfi/__init__.py
- software/glasgow/applet/memory/prom/__init__.py
- software/glasgow/applet/program/m16c/__init__.py
- software/glasgow/applet/video/vga_output/__init__.py
- software/glasgow/gateware/__init__.py
- software/glasgow/gateware/fx2_crossbar.py
- software/glasgow/gateware/i2c.py
- software/glasgow/gateware/lfsr.py
- software/glasgow/gateware/pads.py
- software/glasgow/gateware/uart.py
- software/glasgow/target/hardware.py
- software/pdm.min.lock
- software/pdm.toml
- software/pyproject.toml
- software/tests/gateware/test_i2c.py
- software/tests/gateware/test_uart.py
There are still a few deprecation warnings that appear when running tests with `PYTHONWARNINGS=all` (primarily https://github.com/amaranth-lang/amaranth/issues/1402), but the bulk has been addressed.
I have not upgraded the tests, mainly because there was something *absurdly cursed* going on to allow interleaving Amaranth simulation code and asyncio code, and I don't remember how I made that work nor do I know how to upgrade it really.
> Migrate to Amaranth 0.5

- software/tests/support/test_endpoint.py
I'm not entirely sure about the change in the test function itself. It does run successfully, but I don't know if it's a good idea.
> software: Fix typo, call the right test function

- .github/workflows/main.yml
- firmware/fpga.c
- firmware/glasgow.h
- software/glasgow/device/hardware.py
Fixes #552, previously reported as #96 but not fully addressed.
The minimum delay (3×t_RC for onboard bulk capacitance) is 18 ms, the actual delay implemented is 250 ms, to account for capacitance in the device under test as well.
RevAB devices are not affected.
In addition to the primary issue, another issue was discovered, where turning off the FIFO bus was causing phantom zero bytes to be received by applets, which could then exhibit undesired operation. This was addressed as well by disabling the FIFO bus after and not before reset.
The code size does not change because some code was moved to improve sdcc codegen.
> Turn off Vio on revC before resetting FPGA as a safety measure

- CODEOWNERS
Turns out being a member of a code owner group doesn't allow you to merge your own PR to the files you own, but being an individual that owns the same files does.
Cursed.
> Revert code owners back to what they were before

- software/glasgow/access/direct/multiplexer.py
This PR alters the object returned by `get_{in,out,inout}_fifo()` to also have a `.stream` property, containing an Amaranth stream object whose ports are the `.[rw]_{rdy,en,data}` signals of the FIFO port. It is a part of our gradual migration to the new infrastructure in Amaranth 0.5.
An alternative to this design is to make the FIFO port object itself an interface object that can be connected to Amaranth streams. This was not done because of the `in_fifo.flush` signal, which is sampled regardless of the `in_fifo.stream.valid` (aka `in_fifo.r_en`) signal, and which therefore cannot be a part of the payload. (Even if it was, it would be inconvenient to connect to the IN FIFO port stream if it always included packetization; the closest stream equivalent of `flush` is the `end`/`last` …
> Expose gateware-side FIFO ports as Amaranth streams

- software/glasgow/applet/video/vga_output/__init__.py
- software/glasgow/platform/generic.py
- software/glasgow/platform/ice40.py
Without this the use of a PLL is completely unsound. The `ResetSynchronizer` is necessary since the `LOCK` signal is, as far as I can tell, not synchronized to the output clock.
> platform.ice40: reset `odomain` if instantiated PLL is unlocked

- firmware/main.c
The comment talks about devices which find themselves without a USB address, which implies that power is present, but data isn't.
> firmware: fix comment about power-only USB cables. NFC

- software/glasgow/access/__init__.py
- software/glasgow/access/direct/multiplexer.py
- software/glasgow/applet/interface/jtag_openocd/__init__.py
- software/glasgow/applet/interface/jtag_probe/__init__.py
- software/glasgow/gateware/pads.py
- software/glasgow/gateware/ports.py
Unlike the old `Pads` mechanism, the new `PortGroup` is a proper drop-in replacement for the object returned by `platform.request(..., dir={...: "-"})` and so any gateware built for Glasgow should be usable also outside of it.
Yay for interoperability! :tada: 
This interface can and should be used to upgrade all of the other applets, now.
> Introduce a concept of gateware port groups

- software/glasgow/applet/display/pdi/__init__.py
Another one for #599, this time a slightly more complex case:
1. The applet uses `applet.interface.spi_controller.SPIController{Subtarget,Interface}` which stays at the old pads API;
2. `__pins` were used to call `access.add_pin_argument` - this loop has been unrolled, as I assume removing `__pins` takes precedence?
> applet.display.pdi: modify to use port groups.

- docs/manual/src/conf.py
`linkcheck_retries` defaults to 1 [1], which isn't great for running checks across the Internet, on a few dozen different servers, across thousands of CI runs.
This wasn't tested, but my naïve expectation is that the option works as documented. Not knowing what retry timeout is used is a bit unsettling, but I guess we'll just see if this helps.
[1] - https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-linkcheck_retries
> manual: increase retry count for linkcheck

- software/glasgow/access/direct/multiplexer.py
This can come up when a `--pins-x ''` argument (or no argument at all) is provided, and zero pins are accepted by the applet for it.
In principle, `PortLike` can have a zero length. However, instead, `None` is returned. This is for two reasons:
- Constructing an empty `GlasgowPlatformPort` is surprisingly annoying.
- Handling a case of a zero length port separately from a case of no port being provided at all seems like making I/O cores more complex with no upside to it.
> access.direct.multiplexer: accept empty list in `get_port()`

- docs/manual/src/conf.py
- software/glasgow/cli.py
- software/glasgow/support/arepl.py
- software/glasgow/target/hardware.py
- Bitstreams are now always built in verbose mode (what previously required `AMARANTH_verbose=1`).
- Instead of going to stdout/stderr, Yosys and nextpnr output is now captured by Python host and directed to the normal log at TRACE level. This can be viewed with `-vv` or `-v -F build` CLI options.
- Build logs are considered a product and are cached together with the built bitstream. Absence of a build log (e.g. for bitstreams built before this change) triggers a full rebuild.
- If a bitstream is retrieved from the cache, the build log is logged in the same way as if the build was executed anew.
- If a build fails, the build log is (instantly) output at INFO level, with an error message indicating either this or that `-q` needs to be removed.
- Like the bitstream itself, the build log is …
> Greatly improve quality of life for viewing bitstream logs

- software/glasgow/support/endpoint.py
- software/tests/support/test_endpoint.py
Some protocols start with the server sending some data as soon as the client connects. If such data is not sent, the client will not proceed with its first message.
When send is called before a client is connected, it is immediately discarded. To wait for data sent by the client, a server implementation can call recv_wait. This commit makes recv_wait return after a client connects, too.
TODO:
> support.endpoint: allow waiting for incoming connection.

- software/glasgow/platform/generic.py
Due to a mistake only the lowest pin of a multi-pin port would be actually driven.
> platform.generic: fix value driven on `oe_port`

- software/glasgow/applet/memory/prom/__init__.py
Part of #599.
This one fails with a nasty stacktrace if `--pins-a` isn't set:
```
$ venv/bin/glasgow build  --rev C3 memory-prom
File "/home/q3k/Projects/glasgow2/software/venv/bin/glasgow", line 8, in <module>
sys.exit(run_main())
^^^^^^^^^^
File "/home/q3k/Projects/glasgow2/software/glasgow/cli.py", line 939, in run_main
exit(asyncio.run(main()))
^^^^^^^^^^^^^^^^^^^
File "/run/current-system/sw/lib/python3.11/asyncio/runners.py", line 190, in run
return runner.run(main)
^^^^^^^^^^^^^^^^
File "/run/current-system/sw/lib/python3.11/asyncio/runners.py", line 118, in run
return self._loop.run_until_complete(task)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/run/current-system/sw/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
return …
```
> applet.memory.prom: modify to use port groups.

- software/glasgow/gateware/analyzer.py
- software/tests/gateware/test_i2c.py
This only partially addresses the issue. The old testbenches are going to be removed before Amaranth 0.6 is released, but we have a fair amount of tests still using those.
> Update for some of the deprecations in Amaranth 0.5

- software/glasgow/applet/program/avr/__init__.py
- software/glasgow/applet/program/avr/spi/__init__.py
Before this commit, it was not clear that the filename suffix determines the file format. After this commit this is made clear in the text, and also invalid filenames are rejected at argument parsing stage.
Inspired by, and supersedes, #623.
> applet.program.avr: improve CLI experience for memory arguments

- software/glasgow/cli.py
On my machine:
before:
real    0m1.258s
user    0m1.172s
sys     0m0.077s
after:
real    0m1.010s
user    0m0.911s
sys     0m0.096s
That's a 20% improvement essentially for free!
> cli: speed up startup by not importing all test modules

- software/glasgow/applet/interface/swd_openocd/__init__.py
> applet.interface.swd_openocd: improve formatting of help text

- software/glasgow/applet/interface/i2c_initiator/__init__.py
- software/glasgow/applet/interface/i2c_target/__init__.py
- software/glasgow/gateware/i2c.py
- software/tests/gateware/test_i2c.py
Also, update the I2C core to handle the same.
Part of https://github.com/GlasgowEmbedded/glasgow/issues/599.
> applet.interface.i2c_{initiator,target}: modify to use port groups

- software/glasgow/access/direct/arguments.py
- software/glasgow/access/direct/demultiplexer.py
- software/glasgow/access/direct/multiplexer.py
- software/glasgow/applet/display/pdi/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/interface/spi_flashrom/__init__.py
- software/glasgow/applet/interface/uart/__init__.py
- software/glasgow/applet/memory/_25x/__init__.py
- software/glasgow/applet/program/avr/spi/__init__.py
- software/glasgow/applet/program/nrf24lx1/__init__.py
- software/glasgow/applet/radio/nrf24l01/__init__.py
- software/glasgow/gateware/uart.py
Amaranth supports inversion for any pin and for any I/O core on the I/O buffer level. This mechanism obviates the need for ad-hoc inversion in any applets, but was not exposed until now. Any pin can now be inverted via the command-line interface using one of the following syntaxes:
* single pin: `--pin-x 0#`
* pin range:  `--pins-x 0:8#`      (inverts all of them)
* pin list:   `--pins-x 0,1#,2#,3` (inverts only specified pins)
Pull-ups configured for a pin with inversion get converted to pull-downs and vice versa.
The ad-hoc inversion functionality is now removed from all other applets, since it is not needed, rather sparsely tested, and complicates upstreaming to amaranth-stdio (which has no need for ad-hoc inversion and will not accept it).
> Implement selective pin inversion with `--pin-x 0#` CLI options

- software/glasgow/applet/control/servo/__init__.py
Part of #599.  
This one seems straightforward. I tested that it builds for revC3 with no errors, with and without a `--pin-out` argument.
> applet.control.servo: modify to use port groups

- software/glasgow/applet/interface/ps2_host/__init__.py
> applet.interface.ps2_host: modify to use port groups

- docs/manual/src/use/basic.rst
- docs/manual/src/use/repl-script.rst
- software/glasgow/applet/__init__.py
I had some confusion in the Glasgow real-time chat channels recently around when it would be appropriate to write an applet vs. to write a subcommand; subsequently, I had more confusion when I was reading the source code around how applets were defined.  This pull request shores up the documentation in a few ways:
* Adjusts the getting started guide to now read as a suggested flow -- both a flow for first steps in using the device, and a suggested conceptual flow to understand applets (where they come from, and how they can be used).
* Tweaks usage to always refer to the command line tool as `glasgow`, but the hardware or environment as "Glasgow".
* Reorganizes the documentation to make the "applet" the central concept.
* Adds a link to how applets are enumerated, for silly people who are …
> docs: provide a more gentle introduction to applets

- software/glasgow/support/lazy.py
`if lazy_obj:` didn't work with e.g. `str` because `str.__bool__()` does not exist.
> support.lazy: make `__bool__` work

- docs/manual/src/develop/firmware.rst
I have tested all three install commands in docker containers for each of those systems.
**Note that at the moment on fedora:latest it doesn't build because the name of the "sdcc" executable is "sdcc-sdcc".**
Fedora can be made to build by running `ln -s /usr/bin/sdcc-sdcc  /usr/bin/sdcc`
Not sure if we should mention that in the documentation, or make the libfx2 makefile autodetect it.
> docs: Complete list of firmware build dependencies

- docs/manual/src/develop/firmware.rst
Looks like fedora doesn't automatically pull in the libusb1 package if the python bindings are installed
> documentation: also add the package 'libusb1' to the fedora dependencies

- firmware/adc_adc081c.c
- firmware/dac_ldo.c
- firmware/fpga.c
- firmware/glasgow.h
- firmware/main.c
> Optimize code size (and speed) by using bit access instructions when accessing IO* registers

- docs/manual/src/develop/firmware.rst
For reference:
Fedora changelog:
Fedora readme for SDCC:
> manual: develop/firmware: add note to fedora tab about path

- firmware/adc_ina233.c
Note: on the _set_ side the check cannot be removed, because it also affects the MFR_ALERT_MASK register
> firmware: remove unnecessary check (+25 bytes XRAM).

- firmware/main.c
Whoops. 
I've introduced a bug here in https://github.com/GlasgowEmbedded/glasgow/pull/651
What happens when the goto path is taken is that EP0 is stalled twice, and HSNAK is cleared twice.
It's probably an almost zero probability that a new control transfer would arrive before the function returns,
but it's still a bug in my code, so apologies.
> firmware: move factored-out ep0 stall to end of fn (+13 bytes XRAM).

- firmware/main.c
Everything that handle_pending_usb_setup() does has to be either:
USB_RECIP_DEVICE|USB_TYPE_VENDOR|USB_DIR_IN
or:
USB_RECIP_DEVICE|USB_TYPE_VENDOR|USB_DIR_OUT
Checking these two conditions again and again wastes memory
> firmware: factor out superset bmRequestType check (+116 bytes XRAM).

- firmware/main.c
If a control transfer is rejected, in some cases `pending_setup` will remain true. Then the main loop will keep entering `handle_pending_usb_setup`, and there is a race condition with the `handle_usb_setup()` interrupt handler. Often the handle_usb_setup() interrupt handler will prevent follow-up correctly formed setup packets from completing.
note: This bug was present before my code size optimization patches too.
> firmware: bugfix: rejected control transfer lingers (-2 bytes XRAM).

- software/glasgow/applet/interface/qspi_controller/__init__.py
- software/glasgow/applet/interface/qspi_controller/test.py
- software/glasgow/applet/memory/_25x/__init__.py
- software/glasgow/applet/memory/_25x/test.py
- software/glasgow/gateware/iostream.py
- software/glasgow/gateware/qspi.py
- software/pyproject.toml
- software/tests/gateware/test_iostream.py
- software/tests/gateware/test_qspi.py
Remaining work:
- https://github.com/amaranth-lang/amaranth/issues/1418
- https://github.com/amaranth-lang/amaranth/issues/1405
- https://github.com/amaranth-lang/amaranth/issues/1417
- https://github.com/amaranth-lang/amaranth/issues/1414
- https://github.com/amaranth-lang/amaranth/pull/1448
- happens inherently for IOx, but was enabled explicitly for SCK
- ~~`memory-25x` makes IO2/IO3 optional~~
- for now IO2/IO3 become mandatory
> An applet for controlling a quad-SPI (QSPI/QPI) bus

- docs/manual/src/conf.py
This is currently breaking #669.
> manual: exempt GitHub from anchor checking as a whole

- software/glasgow/gateware/iostream.py
- software/tests/gateware/test_iostream.py
This also adds a testcase to check the correct sampling time.
> gateware.iostream.IOStreamer: fix bug for incorrect sampling DDR inputs

- software/glasgow/gateware/iostream.py
- software/tests/gateware/test_qspi.py
This changeset:
- Re-Adds just the SimulatableDDRBuffer to IOStreamer (without fixing the wrong latency)
- this time SimulatableDDRBuffer is glitchless thanks to Wanda's idea
- Adds QSPI testcases that test (SDR, DDR) X (divisor=0, divisor=1, divisor=2)
- Makes QSPI testcases more robust by listening on the falling edge of CS as well, instead of sampling it
All newly added tests pass successfully.
This changeset is independent of my other work
> Improve QSPI tests

- docs/manual/src/install.rst
The CLI will only run if libusb is installed.
> manual: add libusb dependency for macOS

- software/glasgow/applet/memory/onfi/__init__.py
Instead of using an external pull-up on R/B# (for instance as shown in this [blog post](https://colinoflynn.com/2024/04/dumping-parallel-nand-with-glasgow/)), it is more convenient to use an internal one.
This PR adds an option to do that and doesn't change default behaviour.
> applet.memory.onfi: add an option to toggle internal pull-up for R/B#

- software/glasgow/gateware/iostream.py
When i_stream is idle, there is currently nothing that prevents the state machine from changing state between Falling/Rising, toggling phase, and restarting the timer.
This results in lost power, and sometimes shortened clock pulses after an idle period.
Here is what IOClocker output looks like without this PR:
Here is what it looks like with this PR:
Note: I have circled with green the countdown that _is_ expected to complete.
Here's an example of a shortened clock pulse I've seen:
With fix in PR:
> gateware.iostream.IOClocker: Fix phase and state keeps flipping.

- software/glasgow/device/hardware.py
- software/glasgow/target/hardware.py
There have been reports of issues that are suspected to be manufacturing defects related to the I2C bus, for example #688. These issues cause a failure in one of the post-configuration code paths related to the I2C bus, where it's difficult to display a good error message. This commit adds a dedicated health check register and a dedicated error message:
E: g.cli: FPGA health check failed; if you are using a newly
manufactured device, ask the vendor of the device for return and
replacement, else ask for support on community channels
> Add FPGA/I2C health check after bitstream load

- software/glasgow/applet/interface/swd_openocd/__init__.py
Fixes the following error:
```python
m.submodules.srst_buffer = srst_buffer = io.Buffer("o")
^^^^^^^^^^^^^^
TypeError: Buffer.__init__() missing 1 required positional argument: 'port'
```
> applet.interface.swd_openocd: fix missing required port argument

- software/glasgow/applet/interface/analyzer/__init__.py
Some tools (namely libsigrok), expect non empty names
This fixes the following error when importing the output into pulseview.
```
sr: input/vcd: Cannot parse 'scope' directive
```
relevant code in libsigrok
https://github.com/sigrokproject/libsigrok/blob/f06f788118191d19fdbbb37046d3bd5cec91adb1/src/input/vcd.c#L661-L665
> applet.interface.analyzer: set scope name to something not empty

- software/glasgow/applet/control/si535x/__init__.py
- software/pyproject.toml
This applet has been tested with Si5351A. It can read/write registers and program the clock generator using a CSV register map as exported from ClockBuilder Pro.
> Add an applet for controlling Si5351A/B/C and compatible clock generators

- software/pdm.min.lock
- software/pyproject.toml
Addresses an issue where Amaranth uses a deprecated and now-removed `read_ilang` Yosys command.
> Update to Amaranth 0.5.4

- software/glasgow/applet/internal/selftest/__init__.py
Something I've noticed fairly often is users trying out the self-test and interpreting "broken" as a test fail. I think it'd be clearer to say those test modes are "not supported" instead.
> applet.internal.selftest: label 'broken' tests as 'not supported' instead

- software/glasgow/access/direct/arguments.py
- software/glasgow/access/simulation/arguments.py
- software/glasgow/applet/interface/qspi_controller/__init__.py
- software/glasgow/applet/memory/_25x/__init__.py
It was unclear how the IO0-3 pins correspond to COPI/CIPO/WP/HOLD pins. Add the IO pin names to the pinout drawings for memory-25x, and add the correspondence to `--pins-io` help message.
> applet.{memory.25x,interface.qspi_controller}: improve pins help message.

- software/glasgow/device/hardware.py
This has no functional difference but makes logs 4× shorter at `-vv` verbosity.
> device.hardware: download bitstream in bigger chunks

- docs/manual/src/conf.py
- software/glasgow/cli.py
- software/glasgow/support/arepl.py
Asyncio returns from the event loop if a future raises `SystemExit`, and the async console wraps the code it runs in a future.
Also, it looks like Python 3.13 [broke](https://github.com/python/cpython/issues/129900) `exit()` in an interactive console:
We handle that case properly.
> support.arepl,cli: intercept `SystemExit`.

- software/glasgow/applet/interface/spi_flashrom/__init__.py
This tripped me up when I went from `memory-25x` to `spi-flashrom`, thinking something between glasgow's host side and flashrom broke.
I sort of assumed it would follow the same (excellently described, by the way!) default pinout as `memory-25x` because that applet explicitly mentioned `spi-flashrom`.
> applet.interface.spi_flashrom: change default pin assignments to be like memory-25x

- software/glasgow/applet/program/avr/__init__.py
- software/glasgow/database/microchip/avr.py
There are two changes here:
1. Adding the ATmega8 to the database of AVR microcontrollers. `erase_time` was chosen to match the other entry with an `erase_time`, since *not* having one seemed to lead to issues with verifying what had been written, and this one seems to work fine
2. Fixing up the `program-avr-spi` applet so it doesn't give a traceback whenever you're doing something with an unidentified device
For an explanation of the second one, see the following output I got before adding the ATmega8:
```
% glasgow run program-avr-spi -V 5 --pin-reset 0 --pin-sck 1 --pin-cipo 2 --pin-copi 3 identify
I: g.device.hardware: device already has bitstream ID 57b5cdebb6d0d20034246a56c317b332
I: g.cli: running handler for applet 'program-avr-spi'
I: g.applet.program.avr.spi: port(s) A, B …
```
> Add ATmega8 and fix some minor bugs with program-avr-spi applet

- software/glasgow/applet/audio/yamaha_opx/__init__.py
Originally introduced in #642.
> applet.audio.yamaha_opx: fix typo

- software/glasgow/applet/sensor/scd30/__init__.py
- software/glasgow/cli.py
Alert handling was default enabled which led to unintuitiv usage of the
voltage cli interface, since --no-alert needs to be set if Vio should
just be enabled.
Invert the handling, alerting is now default disabled and --alert can be
used to turn it on.
Fixes https://github.com/GlasgowEmbedded/glasgow/issues/718
Possible improvement would be to issue a warning for the no longer
supported `--no-alert` option instead of the program exiting with
an error about the changed CLI option. Let me know if this is wanted.
> cli: invert voltage alert handling

- software/glasgow/applet/program/ice40_flash/__init__.py
This is an apparent copy-paste error; it checked for the address for the reset pin control register (same as previous fn), then read the done pin reg.
I'm sorry but I don't have the resources (physical hardware nor mental effort) to do actual testing to this, but I couldn't leave it either, so this is almost as-is (i did test that glasgow runs and i can build the applet..).
> applet.program.ice40_flash: read done reg if it exists (not if reset exists)

- .github/workflows/main.yml
Fixes tests by upgrading to Ubuntu 24.04 and removing support for Python 3.9
Happy to rewrite any of the commit messages if necessary.
> Update GitHub Action to Ubuntu 24.04

- software/glasgow/applet/interface/qspi_controller/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/interface/spi_controller/test.py
Forgetting to `async with iface.select():` is a common novice usage error that is frustrating to debug.
> Ensure a chip is selected when transferring bytes via SPI/QSPI interface

- software/glasgow/applet/interface/spi_flashrom/__init__.py
- software/glasgow/applet/interface/spi_flashrom/test.py
- software/glasgow/applet/memory/_25x/__init__.py
Part of #599. `applet.memory._25x` also had to be refactored to use a buffer.
> applet.interface.spi_flashrom: modify to use port groups

- software/glasgow/access/direct/multiplexer.py
- software/glasgow/applet/internal/benchmark/__init__.py
This functionality has never worked correctly and is conceptually unsound and impossible to implement in a generic way.
In exchange the internals get simpler.
> Remove "analyzer throttle"

- .github/workflows/main.yml
- software/glasgow/applet/interface/uart/__init__.py
This applet is often used as an example and until now would return the DemultiplexerInterface object which isn't intended for direct applet end user manipulation, only for applet developers. Instead, it should be wrapped by an applet-specific *Interface object.
Also, the contract for `read()` (with `length = None`) was confusing.
> Modernize the UART applet

- software/pdm.min.lock
- software/pyproject.toml
pyvcd 0.2 has issues with strings in Amaranth simulator waveform dumps.
> software: bump pyvcd lower bound

- software/glasgow/access/direct/multiplexer.py
This was missed in commit 8dc3d8ff2 and caused UnusedElaboratable warnings for every created FIFO.
> FIFO ports should not be elaboratable

- software/glasgow/applet/debug/mips/__init__.py
- software/glasgow/applet/interface/jtag_openocd/__init__.py
- software/glasgow/applet/interface/spi_flashrom/__init__.py
- software/glasgow/applet/interface/swd_openocd/__init__.py
- software/glasgow/applet/interface/uart/__init__.py
- software/glasgow/applet/video/ws2812_output/__init__.py
- software/glasgow/protocol/nbd.py
- software/glasgow/support/endpoint.py
- software/tests/support/test_endpoint.py
This would previously cause many applets to not be properly responsive to ^C.
> Fix `ServerEndpoint` to not use asyncio cancellation in an unsound way

- software/glasgow/platform/rev_c.py
- software/glasgow/target/hardware.py
This fixes a regression introduced in commit c97d2d8e.
The pins in the `unused` resource are connected to another pin in order to simplify routing. iCE40 has a weak pullup on all unused pins that we have to disable or it will interfere with operation.
> Disable pullups on revC pins used for routing

- software/glasgow/support/endpoint.py
This considerably improves performance when forwarding large amounts of data.
> support.endpoint: use `dump_hex()` for large data buffers

- examples/out_of_tree/pyproject.toml
- software/glasgow/support/plugin.py
- software/pdm.min.lock
- software/pyproject.toml
Python 3.9 hasn't been in CI for a while and we already are using some Python 3.10 features (`match`, notably).
> Drop Python 3.9 support

- docs/manual/src/use/basic.rst
- docs/manual/src/use/repl-script.rst
- software/glasgow/applet/__init__.py
- software/glasgow/applet/audio/dac/__init__.py
- software/glasgow/applet/debug/arm/arm7/test.py
- software/glasgow/applet/interface/jtag_pinout/__init__.py
- software/glasgow/applet/interface/jtag_pinout/test.py
- software/glasgow/applet/interface/spi_controller/test.py
- software/glasgow/applet/memory/_25x/test.py
- software/glasgow/applet/memory/prom/__init__.py
- software/glasgow/applet/program/ice40_sram/test.py
- software/glasgow/applet/video/rgb_input/test.py
- software/glasgow/applet/video/ws2812_output/test.py
I.e. instead of `glasgow run uart -V 3.3 --pin-rx 0 --pin-tx 1`, you would use `glasgow run uart -V 3.3 --rx 0 --tx 1`.
This is done because the prefix isn't really useful, because it is nice to group related arguments together, like `--sck 3 --sck-freq 1000`, and because it gets ugly when either one or multiple pins are accepted, like `--cs 0` vs `--cs 0,1`. The latter caused a breaking change reecntly when the QSPI controller applet added support for multiple CS pins; we should not allow that to happen again.
> Drop `pin{s,}-` prefix from pin arguments

- .github/workflows/main.yml
- examples/out_of_tree/pyproject.toml
- software/glasgow/cli.py
- software/pdm.min.lock
- software/pyproject.toml
Asyncio is not really usable for complex projects without task groups, which were introduced in Python 3.11. Maintaining a compatibility layer is infeasible.
> Drop Python 3.10 support

- config/70-glasgow.rules
See https://github.com/GlasgowEmbedded/glasgow/issues/441#issuecomment-2847647413.
> Clarify semantics of `uaccess` udev tag in the recommended rules file

- software/glasgow/gateware/cobs.py
> gateware.cobs: don't lose NUL bytes writing end marker into full FIFO

- firmware/fifo.c
- firmware/fpga.c
- firmware/glasgow.h
- firmware/main.c
- software/glasgow/abstract.py
- software/glasgow/cli.py
- software/glasgow/hardware/assembly.py
- software/glasgow/hardware/device.py
- software/glasgow/legacy.py
- software/glasgow/simulation/assembly.py
This commit ties together several changes that align the way FIFOs work with the new API with the way the firmware treats FIFOs. With new API, applets can request up to 4 independent pipes: two OUT and two IN. There is no inherent ties between any of the pipes, in particular they are not paired as IN+OUT.
Until this commit, the gateware would pair pipes into interfaces: one IN+OUT pair per interface. After this commit, each endpoint gets its own interface, independent from all others. Moreover, the firmware is now aware of a pipe reset register in the FPGA, and will reset a pipe in response to the standard Set Interface command. This command would already clear buffers in the FX2, and for correctness it is necessary to reset the complementary buffers in the FPGA too; until now this was …
> Reset FPGA side FIFOs automatically

- software/glasgow/gateware/fx2_crossbar.py
If the skid buffer starts being drained while the skid buffer is still skidding, we still need to direct incoming bytes to the skid buffer, even though the read stream is now ready.  This fixes problems with bytes being dropped on the OUT FIFO.
Fixes #850.
> gateware.fx2_crossbar: fix skid buffer handling.

- software/glasgow/abstract.py
- software/glasgow/applet/interface/qspi_analyzer/__init__.py
- software/glasgow/applet/interface/spi_analyzer/__init__.py
- software/glasgow/hardware/assembly.py
- software/glasgow/simulation/assembly.py
This caused problems with unpowered targets and autosensing level shifters. Making pull on CS# configurable may also be something to do in the future.
> Make SPI/QSPI analyzer pull settings less aggressive (pull high CS# only)

- software/glasgow/abstract.py
- software/glasgow/hardware/assembly.py
- software/glasgow/simulation/assembly.py
In matrix, I talked about only adding shape to HardwareRORegister. I realized that adding it could create issues simulating an applet that references `register.shape` if SimulationRORegister didn't also have a shape property.
I can go back to only changing HardwareRORegister if you'd like.
> abstract: add shape property to AbstractRORegister.

- software/glasgow/gateware/registers.py
- software/glasgow/hardware/assembly.py
- software/tests/gateware/test_registers.py
- Make RW register writes atomic
- Make RW registers be reset by applet reset
> Gateware I2C regsiter improvements

- software/glasgow/applet/internal/benchmark/__init__.py
https://github.com/GlasgowEmbedded/glasgow/commit/58202523422b38175164ceb833a6112e77b6abe3 broke the benchmark applet because the mode register was set just before reset. Changed to set the mode register just after reset.
> applet.internal.benchmark: reorder register writes to happen after reset

- software/glasgow/abstract.py
- software/glasgow/applet/__init__.py
- software/glasgow/applet/interface/swd_probe/__init__.py
- software/glasgow/applet/interface/swd_probe/test.py
- software/glasgow/cli.py
- software/glasgow/simulation/assembly.py
This replaces `GlasgowApplet{,V2}.derive_clock` and `ClockGen.derive`. Eventually `ClockGen` should be removed.
> Add `AbstractAssembly.add_clock_divisor()` building block

- software/glasgow/applet/control/gpio/__init__.py
This is very useful to set strap pins, e.g. if you have a system reset connected to pin `B7` and it must be asserted for JTAG to work:
glasgow multi jtag-probe <...> ++ gpio --pins B7 B7=0
It is also possible to set pins to drive weakly (e.g. use the `B7=H` or `B7=L` as an argument), and to sample pins (e.g. use `B6` as an argument).
> Applet `control-gpio`: allow interacting with pins from CLI

- software/glasgow/applet/interface/uart/test.py
- software/glasgow/gateware/uart.py
Iteration over a `Shape` has not been a thing since Amaranth 0.4, causing a `TypeError` when setting up non-constant parity. Use the reduction XOR operator instead of hand-rolling the parity computation.
Tested that both odd and even parity work, and that mismatched settings generate receive errors, when listening to an FT232R on macOS running CoolTerm. Tested also that a loopback connection works.
Also adds an applet test for this functionality.
> gateware.uart: fix parity computation

- software/glasgow/applet/program/avr/spi/__init__.py
- software/glasgow/applet/program/avr/spi/fixtures/test_api_calibration.json
- software/glasgow/applet/program/avr/spi/fixtures/test_api_eeprom.json
- software/glasgow/applet/program/avr/spi/fixtures/test_api_fuses.json
- software/glasgow/applet/program/avr/spi/fixtures/test_api_lock_bits.json
- software/glasgow/applet/program/avr/spi/fixtures/test_api_program_memory.json
- software/glasgow/applet/program/avr/spi/fixtures/test_api_signature.json
Even though there is no CS line for AVR programming, SPI controller requires the device to be selected before exchanging data.
> applet.program.avr.spi: select SPI device before exchanging data

- software/glasgow/hardware/build_plan.py
- software/glasgow/hardware/toolchain.py
Before this commit, the toolchain module would attempt to run a stub script (`yowasp-yosys.exe`) from the directory where Python is installed (`C:\Program Files\something` usually), but that's not user-writable, and the script is usually in `%APPDATA%`.
After this commit, we check several paths (from most to least specific). We do not check `PATH` at all since our sandbox does not include `PATH`. It would be ideal to use the path from which the `glasgow[.exe]` stub script was run, but since you can use `python -m glasgow` this isn't feasible. ~~It would also work to execute `python -m yowasp_yosys` but this requires a greater restructuring of the toolchain functionality and I'm not sure it's worth it.~~ It would make it impossible to use with `amaranth.build.BuildPlan.execute_local` since …
> Fix non-virtualenv installations with YoWASP on Windows

- docs/manual/src/applets/interface/index.rst
- docs/manual/src/applets/interface/spi_controller.rst
- software/glasgow/applet/display/pdi/__init__.py
- software/glasgow/applet/interface/qspi_controller/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/interface/spi_controller/test.py
- software/glasgow/applet/interface/spi_controller_deprecated/__init__.py
- software/glasgow/applet/interface/spi_controller_deprecated/test.py
- software/glasgow/applet/interface/spi_flashrom/__init__.py
- software/glasgow/applet/program/avr/spi/__init__.py
- software/glasgow/applet/program/ice40_sram/__init__.py
- software/glasgow/applet/program/nrf24lx1/__init__.py
- software/glasgow/applet/radio/nrf24l01/__init__.py
- software/glasgow/gateware/spi.py
- software/tests/gateware/test_spi.py
This also unfortunately removes functionality (only Mode 3 is supported in the new controller, whereas the old one supported all modes), but most devices use either Mode 0 or Mode 3 and don't care which one it is.
> SPI controller: migrate to V2 API

- software/glasgow/applet/__init__.py
Many applets have optional pin arguments for some auxiliary function, but this is currently non-discoverable if they have a default value, since they look exactly the same as a required argument.
> Be explicit if pin is required or optional in the CLI pin help text

- software/glasgow/applet/program/ice40_flash/__init__.py
- software/glasgow/applet/program/ice40_flash/test.py
The old implementation worked fine, but the new one demonstrates how to use composition (and avoids adding any custom gateware).
The high-level functionality is also synchronized with `program-ice40-sram`.
> Modernize use of GPIO in `program-ice40-flash`

- software/glasgow/gateware/qspi.py
- software/glasgow/gateware/spi.py
- software/tests/gateware/test_qspi.py
- software/tests/gateware/test_spi.py
Before this PR, the clock would idle low after the first transaction was completed.
> Fix SPI/QSPI controllers to actually comply with Mode 3

- software/glasgow/applet/bridge/flashrom/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/program/ice40_sram/__init__.py
This parameter is currently just there to make any downstream user stop and consider whether their device actually uses Mode 3 or not. Once SPI modes are implemented properly, it will configure the SPI controller.
> Add stub mode parameter to SPI controller interface

- software/glasgow/cli.py
A typical applet would now have:
* positional arguments
* options
* configuration
In the future we might also unify `add_setup_arguments` with `add_build_arguments`. The argument (no pun intended) to have them be separate was that the latter influences gateware build and the former does not, but this is an artificial and mostly meaningless division, especially with the V2 API.
> cli: simplify/clarify argument group titles.

- software/glasgow/abstract.py
- software/glasgow/applet/bridge/jtag_xvc/__init__.py
- software/glasgow/applet/bridge/probe_rs/__init__.py
- software/glasgow/applet/debug/arm/arm7/__init__.py
- software/glasgow/applet/interface/qspi_analyzer/__init__.py
- software/glasgow/applet/interface/qspi_controller/__init__.py
- software/glasgow/applet/interface/spi_analyzer/__init__.py
- software/glasgow/applet/interface/spi_controller/__init__.py
- software/glasgow/applet/interface/swd_probe/__init__.py
- software/glasgow/applet/interface/uart/__init__.py
- software/glasgow/applet/interface/uart_analyzer/__init__.py
- software/glasgow/applet/internal/benchmark/__init__.py
- software/glasgow/gateware/fx2_crossbar.py
- software/glasgow/hardware/assembly.py
- software/glasgow/simulation/assembly.py
This eliminates a common pitfall for applet authors, where by default the IN FIFO is flushed too often, and very small packets clog the FX2 buffers, causing buffer overflows and data loss. With this change, so long as the host polls the device once per microframe (with XHCI hosts, this can happen even more than once), there will never be a case where an FX2 buffer isn't available, unless the bus is very heavily loaded with other traffic.
There are two cases where more control over flushing is desired.
First, in request/response style protocols, it is useful to flush the IN FIFO once the OUT FIFO is empty, since this reduces time spent waiting for responses. This can significantly improve `probe-rs` throughput, and is still used in that applet.
Second, an applet that produces a stream of …
> Flush IN FIFO once per microframe

- software/glasgow/cli.py
Suggested in a recent conversation on matrix - should make debugging issues a bit easier.
Uses the same guts as `glasgow version`.
> cli: print version info when using --verbose

- examples/applets_without_cli.py
- software/glasgow/applet/__init__.py
- software/glasgow/applet/_legacy.py
- software/glasgow/applet/debug/arm/arm7/test.py
- software/glasgow/cli.py
- software/glasgow/hardware/assembly.py
- software/glasgow/hardware/device.py
- software/glasgow/hardware/platform/__init__.py
- software/glasgow/hardware/toolchain.py
- software/glasgow/support/usb/__init__.py
- software/glasgow/support/usb/libusb1.py
- software/glasgow/support/usb/webusb.py
- software/pdm.min.lock
- software/pyproject.toml
This is very much not mergeable yet. To be completed:
> Abstract out USB communication to enable a future WebUSB backend

- software/glasgow/database/microchip/avr.py
Adds ATtiny1634 to the Microchip AVR database. Tested working for reading and writing with real hardware.
> database.microchip.avr: add support for ATtiny1634

- software/glasgow/applet/__init__.py
- software/glasgow/applet/_legacy.py
- software/glasgow/cli.py
- software/glasgow/hardware/assembly.py
- software/glasgow/hardware/build_plan.py
- software/glasgow/hardware/device.py
- software/glasgow/hardware/toolchain.py
- software/glasgow/support/asyncio.py
- software/glasgow/support/usb/webusb.py
- software/pdm.min.lock
- software/pyproject.toml
> software: add toolchain integration for Emscripten

- .github/ISSUE_TEMPLATE/01-bug-report.yml
This renders as a nice form and prompts the reporter to fill in version and logs (optionally).
> GitHub: add bug report template

- docs/manual/src/install.rst
This command doesn't run correctly unless you quote it. At least not for me with Powershell.
> Update install.rst to add quoting for Windows.
